muikku-calendar/.gitignore
muikku-core-plugins-persistence/.gitignore
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsWorkspace.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
muikku-evaluation-plugin-persistence/.gitignore
muikku-school-data-pyramus-persistence/.gitignore
muikku-school-data-pyramus/.gitignore
muikku-timed-notifications-plugin-persistence/.gitignore

Fix #3444 filter courses in VOPS by curriculum

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js

** Added .includes polyfill, resolves #3474

Added .includes polyfill, resolves #3474

---

muikku/src/main/webapp/resources/scripts/gui/environment.js

Auto join global chatroom

---

.travis.yml

** Enables Course Management side tests in PR's and Builds

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java

Remove MUU from vops

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java

Don't show courses with no permissions in VOPS

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java

** Fixes #3516 vops permissions

---

.travis.yml
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseAccessTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/evaluation/EvaluationTestsBase.java
travis-setenv.sh

Ftr 3517 test changes

---

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss

Ftr 3064 textfield width mobile

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

Use own version of Converse.js

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java

Fixes #3532 AI/ÄI fix in VOPS

---

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss

* Added z-index to word defition elements

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

** Fixes #3483 hide unnecessary features in converse

** Fixes #3483 hide unnecessary features in converse

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRoomSyncScheduler.java

Fixes #3293 chat rooms for workspaces

Ftr 3293 chat rooms for workspaces

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java

Fixes #3513 refactor vops

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/StatusRESTModel.java
muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml
muikku/src/main/webapp/resources/scripts/gui/environment.js

Fix #3238 dont ask for nick in chatrooms

Ftr 3238 dont ask for nick in chatrooms

---

muikku/src/main/webapp/resources/scripts/gui/environment.js

** Fixes #3552 hardcoded MUC hosts in converse

** Fixes #3552 hardcoded MUC hosts in converse

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRoomSyncScheduler.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatUserSyncScheduler.java

Fixes #3550 make chat sync non-persistent

Fixes #3550 make chat sync non-persistent

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss

3540 evaluation word count

---

muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java

- requires Pyramus 609
- requires Muikku permission reset
- resolves #3470

Additional study guider permissions for evaluation

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java

Added filter for old curriculum RUB

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java

Fixes #3570 vops courses not visible

Fixes #3570 vops courses not visible

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java

#3391-RearrangeOPS

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml
muikku/src/main/webapp/resources/scripts/gui/environment.js

Fixes #3558 open chat room boxes minimized

Fixes #3558 open chat room boxes minimized

---

muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml

Fixes #3530 Show separate analytics data for logged-in and logged-out users

#3530 Show separate analytics data for logged-in and logged-out users

---

muikku/src/main/webapp/resources/scripts/gui/environment.js

Fixes #3599 hide converse controlbox by default

Ftr 3599 hide converse controlbox by default

---

muikku/src/main/webapp/resources/scripts/gui/environment.js

Fixes #3588 don't show join/leave messages in chat

Fixes #3588 don't show join/leave messages in chat

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/communicator/communicator-messages.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/communicator/communicator-messages/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/communicator/communicator-messages.ts

Fixes problem with message duplication while scrolling if a new one was
just added.
Fixes the problem with the not appearing messages sent by user to
himself

#3511 Fixes problem with message duplication while scrolling if a new one was

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java

Fixes #3637 vops courses only shown up to 14

Fixes #3637 vops courses only shown up to 14

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/communicator/communicator-messages.ts

#3643  Fixes problem with the not appearing messages send by user to himself. Now standartized.

#3643 Fixes problem with the not appearing messages send by user to himself.

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/ClientPool.java

Closes #3545 
Test this with proper certs before deploying.

Changed trust-all-certs to be active only on development

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java

Fixes #3647 include all enrolled courses in VOPS

Fixes #3647 include all enrolled courses in VOPS

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java

Added null-safe checks for WorkspaceAssessment.getPassing()

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java

Fixes #3668 wrong curriculum courses included in mandatority (VOPS)

Fixes #3668 wrong curriculum courses included in mandatority (VOPS)

---

muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_fi.properties

** Fixes typo in evaluation

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceMaterial.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceNode.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceFolderDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceMaterialDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/base/BooleanPredicate.java

* Added hidden but answered exercises to evaluation
* Added hidden but answered exercises to ToR
Closes #3518

3518 evaluation hidden page

---

muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml
muikku/src/main/webapp/resources/scripts/gui/chat.js
muikku/src/main/webapp/resources/scripts/gui/environment.js

Fixes #3670 activate converse.js on end

Fixes #3670 activate converse.js on end

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view.tsx

Fixes #3652 Replying to own reply. Also prevented duplication of recipients due to the presence of the same user in both recipients and sender of the message to which reply is created.

Fixes #3652 Replying to own reply.

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

Fixes #3671 hide features list in chat

Fixes #3671 hide features list in chat

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsLister.java

Fixes #3708 vops not visible in guider

Fixes #3708 vops not visible in guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js

Bug 3569 mathjax for student

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/forgot-password-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/vars.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dialog.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/form-fields.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/form.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss

Bug 3678 dialog styles

---

muikku/src/main/webapp/resources/scripts/gui/environment.js

Fixes #3685 Don't join rooms automatically

Fixes #3685 Don't join rooms automatically

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml
muikku/src/main/webapp/resources/scripts/gui/chat.js

Fixes #3568, fixes #3564

---

muikku-bom/pom.xml
muikku-core-plugins/pom.xml
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatPrebindParameters.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/XmppCredentials.java
muikku/src/main/webapp/resources/scripts/gui/chat.js

Ftr 3686 prebind for chat

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/main-function.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/text.scss

Ftr 3692 hover effects for list item

---

muikku/src/main/webapp/WEB-INF/templates/flex-main-open.xhtml

* Changes front page's phone number

---

muikku/src/main/webapp/WEB-INF/templates/flex-main-open.xhtml
muikku/src/main/webapp/resources/theme-muikku/sass/flex/frontpage.scss

* Added missing hyphen to muikku-verkko text logo

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

* Conversejs update

---

muikku/src/main/webapp/index.xhtml

* Changed front page's first video to a newer one

---

muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceUserEntityDAO.java

Fix for duplicate workspace users crash

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/feed/FeedSynchronizer.java

Set feedsynchronizer as non persistent shceduler

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js

Removed crash prone and essentially unused query param

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

Closes #3682 
Main changes are made in converse.js project as here we only increase version number. 
Added new div element in converse.js templates and corresponding styling.

* Raised converse version to 1.1.0

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Slightly more informative logging for internal errors

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumPermissionResolver.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/controller/ResourceRightsController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/AbstractPermissionResolver.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/PersonalPermissionResolver.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/UserGroupPermissionResolver.java

Annotation changes that aim to lower server burden

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java

Best guess fix for occasional NPEs when listing announcements

---

muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_workspace_progress.dust
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/records/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/records.scss

Ftr 3762 tor progress indicator

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties

Memo char/word counter localization and bug fix

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java

NPE fix in creating workspace

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataController.java
muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

Evaluation NPE fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_workspace_progress.dust

removed *2 multipliers on the evaluablesDonePercent and exercisesDonePercent

Fixes #3796 Table of records assignment progress lines are not accurate

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/feed/FeedRESTService.java

Fix for RSS feeds returning 404 if even one of the requested feeds is missing

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Do not send communicator messages to students who have ended their studies

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataActiveWorkspaceStudentsUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataInactiveWorkspaceStudentsUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataPersonsUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataStudyProgrammeMembersUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataUserGroupUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataUserGroupUsersUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataWorkspaceUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataWorkspaceUsersUpdateScheduler.java

Fix for schedulers getting stuck to an erroneous batch

---

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java

Null check workspace assessment grade

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-courselist.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-messages.js

Tidied up front page workspace and message widgets

---

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_view_profile.dust
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js
muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss

Closes #3826 
Added Back button, functions well needs to be designed

adds Back button to the user profile in guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/announcements/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/application.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navbar/profile-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/reading-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/entries/announcer.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/articles.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/reading-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/text.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/toc.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/announcer/AnnouncerJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/announcer/AnnouncerJsPluginMessages_fi.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_fi.properties

Closes #3772 
This separates announcement view from announcer quite effectively and add new "components". Also fixes the layout to follow the UI sketches more closely.

Ftr 3772 announcement reading view styling

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js

Fixes #3420 textfields examples not shown when checking

Fixes #3420 textfields examples not shown when checking

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js

Fixes #3421 Dropdown exercises not checked

Fixes #3421 Dropdown exercises not checked

---

muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss

Fixes #3831 Communicator renders heading 1-6 in caps

Fixes #3831 Communicator renders heading 1-6 in caps

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/user/rest/UserPluginRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/profile.js
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfileJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfileJsPluginMessages_fi.properties
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java

Fixes #3798 Changing username fails is username is already in use

Fixes #3798 Changing username fails is username is already in use

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusDataScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchedulerOffsetController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataActiveWorkspaceStudentsUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataInactiveWorkspaceStudentsUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataPersonsUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataRolesUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataStudyProgrammeMembersUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataStudyProgrammeUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataUserGroupUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataUserGroupUsersUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataWorkspaceUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusSchoolDataWorkspaceUsersUpdateScheduler.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusUpdateScheduler.java

- resolves #3848 (allow schedulers to move past failed batches)
- resolves #3849 (support for disabling individual schedulers with plugin settings)

Yet more scheduler changes

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseTestsBase.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderStudentWorkspaceActivity.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderStudentWorkspaceActivityRestModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_workspace_progress.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace_progress_frontpage.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace_progress_materials.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace_progress_materials_fullscreen.dust

- fixes #3827 
- hide assignment progress indicators when there are no assignments

Materials: Fixes issues with assignment progress tracking

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/index.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/main-function.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/message.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/container.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/message.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/pager.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/text.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumJsPluginMessages_fi.properties

Ftr 3850 discussion styling fixes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketTicketController.java

Separate transaction for websocket ticket cleanup

---

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-archive-request-confirm.dust
muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-card.dust
muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js
muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties
muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties
muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation-index.scss

Fixes #3656   evaluation request's archiving
Depends on Pyramus 756  evaluation request's archiving
https://github.com/otavanopisto/pyramus/pull/756

Fix BUG #3656 evaluation request's archiving

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatClientHolder.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatUserSyncScheduler.java

Fixes #3832 xmpp prebind fails

Fixes #3832 xmpp prebind fails

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

Fixes #3880 Chatroom names behaves weirdly

Fixes 3880 Chatroom names behaves weirdly

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/communicator/communicator-messages.ts

Fixes #3887 Removing communicator label won't update message list

Fixes BUG #3887 Removing communicator label won't update message list

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcement-view.tsx

Workspaces for announcement view

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/toolbar.tsx

Added locale to toolbar

---

muikku/src/main/webapp/resources/scripts/gui/chat.js

Fixes #3924 Keepalive converse

Fixes #3924 Keepalive converse

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncerAttachmentUploadServlet.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAttachmentUploadServlet.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/feed/FeedSynchronizer.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsFileUploadServlet.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/MaterialAttachmentUploadServlet.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/cache/CacheConfigs.java
muikku/src/main/java/fi/otavanopisto/muikku/files/TempFileUploadServlet.java
muikku/src/main/java/fi/otavanopisto/muikku/servlet/DustTemplateServlet.java

Input stream housekeeping

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java

- resolves #4001
- NOTE: requires permission reset

Fix for study guiders not being able to create workspace documents

---

muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

Fix for dates in Elastic search results

---

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_profile_workspaces.dust

Fixes #3946 Guider does not show evaluation request status correctly.

Fixes #3946 Guider does not show evaluation request status correctly.

---

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml

Fixes #3979 Converse workspace chat rooms does not open correctly

Fixes #3979 Converse workspace chat rooms does not open correctly

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/records.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/text.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_fi.properties

Bug 4027 studies view incomplete and failed state

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java

Fixes #3927 transcript of records view crashes with evaluations that have no grade

Fixes #3927 transcript of records view crashes with evaluations that have no grade

---

muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace_navigation_wide.scss

Bug 4059 incomplete evaluation

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsBackingBean.java

Study end date support for transcript of records (redesign)

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js

More responsive tolerance for dragging in organizer

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-explanation-widget.js

Field explanation MathML support

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js

Fix for not being able to evaluate workspaces of "past" students

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatPermissions.java
muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml
muikku/src/main/webapp/resources/scripts/gui/chat.js

Closes #4078 Study program leader should be able to create permanent chat room

FTR #4078 Study program leader should be able to create permanent chat room

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusIdentifierMapper.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java

Requires https://github.com/otavanopisto/pyramus/pull/845
Closes #4101

Added CreditLinks to tor

---

muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java

Changed back to checking only the default identifier role. This likely needs to change when there can be users that have access to several organizations but we need more details set in stone before that can be implemented.
Closes #4127

Reverted to default role permission checking

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataOrganizationListener.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/OrganizationEntityController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/OrganizationEntityDAO.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/OrganizationEntity.java
updates_development/organization.xml

Archive organizations

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json

BUG-4230 Broken Dialogs

---

.travis.yml
muikku-atests/pom.xml
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
travis-before-script.sh
travis-setenv.sh

Fixes sauce-testing-bug
Fixes few bugs in tests and sauce connect bug.

Sauce testing bug

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataUserListener.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/EnvironmentRoleEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/OrganizationEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/RoleEntity.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/RoleSchoolDataIdentifier.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java

4128 identifierremoved

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/reading-panel.scss

BUG 4255 announcment reading view layout

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/header.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/button.tsx

BUG-4262 frontpage bubble buttons

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navbar/menu.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/vars.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/hero.scss

Bug 4271 profile icon misaligned

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialFieldAnswerController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialFieldChangeListener.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceMaterialAudioFieldAnswerDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/FileAnswerType.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/FileAnswerUtils.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/WorkspaceAudioFieldIOHandler.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceSystemRESTService.java

File system support and migration tool for audio answers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/footer.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/hero.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/link.scss

BUG - 4275 front page footer wrapping

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/records/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml

* Updated recordRTC library

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js

Audio field recording and retrieving bug fixes

---

muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java

Study guider access to users' workspace activity

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractIntegrationTest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceStudentRestModel.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceUserRestModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-students-active.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-students-inactive.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-teachers.dust
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-users.js
muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java

Optimized workspace members view

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/user-index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/label-share.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/user-index.ts
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/FlagShare.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/StaffMemberBasicInfo.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

GuiderRESTService endpoints are basically copies from UserRESTService so while they look tedious, they should behave the same.
Closes #4286

4286 refactor userindex

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/records/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml

Bump file uploader to 9.28.0

---

muikku-bom/pom.xml

Jackson version bump to 2.8.11

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java

Fixed user search NPE when Elastic data is not in sync with Muikku

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties
muikku/src/main/webapp/resources/theme-muikku/sass/deprecated/flex/_evaluation_evaluate_modal.scss

Ftr 4274 prevent unnecessary second evaluation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/entries/records.ts

Feature #4162

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx

4304 recipients

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator-newmessage.js

Recipient search changes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/announcements/index.ts

Fixed bug with announcement update

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/hops_readable.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/vops.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student/main-chart.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students/student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-sub-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/chart.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/file-uploader.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/vops.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_fi.properties

Fixes #4329 
* Multiple white space removals
* Student name and email rendering fixes
* Wrong header in vops and statistics
* Adjusted localization for hops and vops
* Adjusted markup for vops (not finnished yet)
* Fixed font in charts
* Fixed layout issues of fie uploader/uploaded file lists in mobile
* Removed deprecated text class name from hops
* Fixed vops rendering in mobiles

BUG-4329 Guider layout issues

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/chat/model/WorkspaceChatSettings.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java

Temporary crash fix when workspace chat settings update endpoint is called with invalid data

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses/course.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/body-scroll-loader.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/reading-panel.scss
muikku/src/main/webapp/resources/theme-muikku/sass/deprecated/flex/_evaluation_evaluate_modal.scss

Bug 4340 production issues

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js

Fix for students incorrectly marked as graded in evaluation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js

Yet another workspace re-evaluation overlay bug fix

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatSyncController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/UserIndexer.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/user/rest/UserEntityFileRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialsBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceSystemRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/EnvironmentUserController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserSchoolDataIdentifierController.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java

Refactored user role fetching

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/evaluation/main-view.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js

FTR 4368 Remove old evaluation icon

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application.tsx
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerJsPluginMessages_fi.properties

Fixes #4370 
Additionally added "Open courses" to course picker's selection is user is not logged in. Other options naturally are not visible at the same time.

Bug 4370 as teacher coursepicker

---

muikku/src/main/webapp/WEB-INF/templates/deprecated/flex-base.xhtml

fixed 4364

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts

BUG-4378 labels and flags order

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/i18n.ts

BUG-4380 quotation in subject field

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/index.ts

BUG-4367 communicator unread message

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student.tsx

BUG-4386 Usergroups loading in guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/dialogs/new-edit-announcement.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-thread-reply.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/new-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/reply-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/ckeditor.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/autocomplete.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/environment-dialog.scss

Fixes #4390 
Just updated ckeditor to the last version seemed to do the trick c:

updated ckeditor

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js

Set last visited workspace material page for own workspaces only

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/aside.tsx

Scroll to top when announcement is clicked.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx

Bug 4405 discussion message edit

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/workspaces-panel.tsx

Added sort function to workspaces in front page

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/dialogs/new-edit-announcement.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/modify-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/dialogs/new-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students/student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/label-share.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/modifiers.ts
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Fixing missing nickname bug

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/body-scroll-loader.tsx

added fallback to document.body.scrollTop for buggy browsers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/announcements/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/announcements/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcement-view.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/dialogs/new-edit-announcement.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/index.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/article.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/label.scss

added forgotten usergroups

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/footer.scss

BUG-4417 Footer layout broken

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/dialogs/workspace-signup.tsx

This should be fixed other than the dialog didn't close up...
I just made the dialog close.
Fixes #4385

Closing dialog after signup

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/navbar/profile-item.tsx

Bug 4398 discussion category does not load properly

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js

Remove audio file WAV/FLAC constraint

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
muikku/src/main/webapp/resources/theme-muikku/sass/deprecated/flex/_audio-field.scss

FTR-4422 Download audio icon

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar/labels.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/link.scss

BUG-4408 Wrong styling for selected labels/flags

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/yo.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/yo.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/yo.ts

Bug 4435 yo view has a loading issue

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/WorkspaceAssessmentState.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

New endpoint to query workspace evaluation state for a student

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx

Use search instead of searchString

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatSyncController.java

Fix NPE if workspace has no WorkspaceChatSettings entity

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java

Email notification of a workspace supplementation request

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJournalController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceJournalEntryDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceJournalEntryRESTModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js

Refactored journal REST endpoints

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/summary.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/yo.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/summary.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/records.ts

summary statistic data in place

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Fixed next, past and current terms to match the specs

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Fixed text on matriculation form course count validation

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Fixed matriculation attendance rules

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceJournalComment.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJournalController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceJournalCommentDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceJournalCommentRESTModel.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceJournalEntryRESTModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js
muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java
muikku/src/main/java/.gitignore
updates/1.086/190228-journal-comments.xml

- resolves #4473
- fixes #4478

Journal student load bug fix, back-end support for journal comments

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Changed matriculation form mandatory rule to check for exactly 4 courses

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/records.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/main-function/navbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/records.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/workspaces.ts

This makes use of the new endpoint provided by Pasi.
Fixes #4467 
Fixes #4462 
Hopefully Fixes #4461

Bug 4467 refactor to r and others

---

matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/MatriculationSchoolDataController.java

4489 matriculation enrollment expiration

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Removed term validation feature from matriculation sign-up form

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Hotfix 4502 matriculation exam form text change

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Fixed issue #4512

---

muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_fi.properties

Email notification no reply reminder

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

- changed number of mandatory courses field to accept numeric values only
- removed unimplemented REQUIRES_ATTENTION value from form state
- resolves #4524

Enrollment form changes

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Fixed issue #4526

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts

Show students' past workspaces in Guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx

arrow naming changes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts

Removes vops from guider and studies

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js

Fix to archive evaluation requests correctly even after line changes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceSystemRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java

Workspace student sync bug fixes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

- fixes otavanopisto/muikku#4548

NPE fix (and additional logging) to listing workspace members

---

matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationCurrentExam.java
matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/matriculation-link.tsx
muikku-core/src/main/java/fi/otavanopisto/muikku/controller/PluginSettingsController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/ClientPool.java

Plugin setting for groups eligible for matriculation enrollment

---

matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationRESTService.java
matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/restmodel/MatriculationExamEnrollment.java
matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/MatriculationExamEnrollment.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusMatriculationExamEnrollment.java

* Added DegreeType to matriculation form
* Added UNKNOWN SchoolType to matriculation form
Depends https://github.com/otavanopisto/pyramus/pull/980
Closes #4566

Added DegreeType to matriculation form

---

matriculation-plugin/src/main/resources/jade/enrollment-notification.jade

Fixes reference to repeat field incorrectly addressed as restartExam

Fixed reference to correct field

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java

Teachers should only see their own students in guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js

TOC icon for withdrawn assignments that have been evaluated

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcements.tsx

Closes #4440 Announcer tool shows extra character

---

muikku/pom.xml

Remove unused project dependencies

---

matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationNotificationController.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/base-main-function.ts
muikku-core/src/main/java/fi/otavanopisto/muikku/mail/Mailer.java
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

* Fixed issue with profile picture url when server uses different port
* Removed two script references that don't seem to exist anymore (caused RES_NOT_FOUND references)

Minor fixes 20190514

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student/workspaces.tsx

Guider - Students' workspaces not in alphabetical order

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/header.tsx

* Submit application link changes

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/records/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js
pom.xml
travis-script.sh

Various audio recording fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/helpers.ts

Fixes the bug when 25th student isn't shown at all

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx
matriculation-plugin/src/main/resources/jade/enrollment-notification.jade

4671 matriculation fixes

---

matriculation-plugin/src/main/resources/META-INF/resources/jsf/matriculation/index.xhtml
matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx
matriculation-plugin/src/main/resources/subjects.json

* Reworked drafting
* State-dependent messages on the last page (save in progress, successful save, failed save)
* Saame subjects
Closes #4675

4675 matriculation issues part 2

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses.tsx
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerJsPluginMessages_fi.properties

BUG-4647 Course Picker's empty message

---

muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-core-plugins-persistence/src/main/java/.gitignore
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/announcer/model/Announcement.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementsViewBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/WorkspaceAnnouncementsViewBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/dao/AnnouncementDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/DiscussionBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/UserGroupEntityDAO.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java
muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
muikku/src/main/webapp/WEB-INF/templates/base.xhtml
updates_development/organization.xml

4708 discussion organization

---

matriculation-plugin/src/main/resources/jade/enrollment-notification.jade
muikku-core-plugins-persistence/src/main/java/.gitignore

Removed SSN from matriculation enrollment notification email

---

matriculation-plugin/src/main/resources/jade/enrollment-notification.jade

Removed matriculation enrollment email season

---

matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

Matriculation exam enrollment fix for Edge (possibly Safari)

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js

Doubled students' assumed lines in Records view

---

muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/OrganizationRESTModel.java

Address change fix

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/StudentPayload.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserController.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Rudimentary student creation support

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/feed/FeedSynchronizer.java

Catches redirect exceptions when updating feeds

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/MaterialController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/HtmlMaterialRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_fi.properties
muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java

Restrict operations affecting answers in published workspaces to admins only

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/HtmlMaterialRESTService.java

Material revert NPE fix

---

muikku-atests/pom.xml
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java
muikku-pyramus-oauth/pom.xml
muikku-school-data-pyramus/pom.xml
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Requires https://github.com/otavanopisto/pyramus/pull/1081

Changed evaluation fee detection to studyprogramme property

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js

Prevent duplicate grade and supplementation request saves

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/MatriculationExam.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusMatriculationExam.java

Changes cherrypicked from 855 that fix the fetching of matriculation exams from Pyramus

Fixes fetching matriculation exams from Pyramus

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Material attachment deletion NPE fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js

Fixes mixed up memo field example answers in evaluation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js

Fix for "withdrawn exercises"

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/MaterialMetaRESTService.java

Material meta database constraint violation fix

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataUserGroupListener.java

Restore removed user groups that were miraculously resurrected elsewhere

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

List workspace staff members across organizations

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityName.java

Fixes a couple of 403s in evaluation

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Do not send communicator messages to students' past study programmes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/auth/AbstractAuthenticationStrategy.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

4922 disable credentials on study break

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/dao/CommunicatorMessageDAO.java
updates/1.091/200427-communicator_index.xml

Communicator trash folder rewrite

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Student archive 404 bug fix in evaluation

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/StudyProgramme.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserController.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/StudyProgramme.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusStudyProgramme.java

Endpoint for study programmes

---

muikku-atests/src/test/resources/muikku-data/test/test-data.sql
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataOrganizationListener.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/OrganizationEntityController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/OrganizationEntityDAO.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/base/Archived.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/OrganizationEntity.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/OrganizationWorkspaceVisibility.java
updates/1.092/200514_organizationworkspacevisibility.xml

Added workspaceVisibility to OrganizationEntity

---

matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationIndexBackingBean.java
muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorIndexBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/DiscussionBackingBean.java
muikku-core/src/main/java/fi/otavanopisto/muikku/auth/AbstractAuthenticationStrategy.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/CurrentUserSession.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/RestAuthentication.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/RestSessionControllerImpl.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/SessionController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/SessionControllerDelegateImpl.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/local/LocalSessionControllerImpl.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/local/LocalSessionRestAuthentication.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/RestSessionFilter.java
muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java

Refactored IsActive resolving from login

IsActive refactor

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/TestUtilities.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/CourseBuilder.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java

** Fixes no compile bug

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SchoolDataSearchReindexListener.java

Reindex workspaces before users

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/journal/CourseJournalPageTestsBase.java

** Journal tests

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss

4979 - Header font sizes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/workspace/navbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/link.scss

4978 - workspace color to menu icons

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/iframe.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/link.tsx

Added absolute url logic on links and iframes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/header.tsx

4995 - Workspace image loading

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/multiselect-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx

Fixes #4977 which caused the page to crash when two ckeditors were loaded in parallell

CKEditor using uuid rather than processor clock time

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts

Closes #5003 
Fixes the bug with the journals not loading properly

Restored scroll infinite

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pager.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/pager.scss

5004 discussion pagination styles

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Constraint safe material reply generation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/content-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/progressData.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/header.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/content-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dropdown.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/hero.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/meta.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/toc.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/workspace-activity.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties

4996 workspace progress indicators

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/SaveFieldAnswerWebSocketMessageHandler.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialReplyController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Reworked #5013

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss

Closes #5012 #5011
Layout issues with table cell fixed here as well as it was only one css property change

5012 checkbox/radio buttons layout with long text

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application.tsx

4950 - Study diary new entry for  mobile devices

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss

5024  - Video embed's img overflow

---

muikku-atests/pom.xml
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/announcer/CourseAnnouncerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/picker/CoursePickerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java

5001 redesign test p1

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts

Removing caches on composite replies

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/progressData.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/header.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/workspace-activity.scss

5035 - ProggressData style fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx

5023 Textfield's width

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-panel/application-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-panel/components/application-panel-body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-panel.scss

5029 mobile study diary teachers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/dialogs/upload-image.tsx

fixes the image editor aspect ratio

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/image.tsx

Added numeric checks for the image so that the result is finite

---

muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/StaffMember.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

Role to staff member REST object

---

muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

Organization management study guider and study programme leader support

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/videos.tsx

5101 - Empty front page video removal

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx

5094 - More languages to CKEditor's language dropdown

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/videos.tsx

5110 - New video to the front page

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/footer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/footer.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/link.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_fi.properties

5081 - accessibility directive link added to the footer

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/hops_readable.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-sub-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/profile-element.scss

5115 - studies view mobile fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/zoom.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/zoom.scss
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Closes #5119 #5057 
Solved 2 issues together as they were sort of related and easy to fix.

5119 & 5057 - Mobile zooming and image zooming

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/mixins.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/form-elements.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/base-main-function.ts

Closes #5116 
This removes converseJS initialization for users that has set chat active as we are developing our own and better version of it.

5116 - workspace members search ui broken

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/environment-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/environment-dialog.scss

5106 - CKEditor height calculated incorrectly

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/modifiers.ts

5129 - Added allow attribute to translations

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/websocket.ts

Fixed websocket not reconnecting after a lost connection

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/base-main-function.ts

5139 - Added communicator unread badge back

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceMaterialAudioFieldAnswerClip.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceMaterialFileFieldAnswerFile.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialFieldAnswerController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceMaterialAudioFieldAnswerClipDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceMaterialFileFieldAnswerFileDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
updates/1.095/201006-file-contenttype.xml

Make content type of uploaded binaries optional

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java

Staff members are considered active in communicator

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java

Fix excessive error logging with archived usergroups

---

muikku-core/src/main/java/fi/otavanopisto/muikku/users/CreatedUserEntityFinder.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

User creation wait fix

---

muikku/src/main/webapp/resources/scripts/widgets/controllers/websocket.js

Old websocket create fix

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java

- permission check fix when updating workspace chat settings
- 403 fixes when asking chat status when not logged in

Minor chat bug fixes

---

.github/workflows/announcerTest.yml
.github/workflows/communicatorTest.yml
.github/workflows/courseAnnouncerTest.yml
.github/workflows/courseJournalTest.yml
.github/workflows/courseManagementTest.yml
.github/workflows/courseMaterialsTest.yml
.github/workflows/courseTests.yml
.github/workflows/courseUsersTest.yml
.github/workflows/coursepickerTests.yml
.github/workflows/discussionsTest.yml
.github/workflows/flagsTest.yml
.github/workflows/guiderTest.yml
.github/workflows/indexPageTest.yml
.github/workflows/newevaluationTest.yml
.github/workflows/restTest.yml
.github/workflows/torTest.yml
.github/workflows/userTest.yml
.travis.yml
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/picker/CoursePickerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
travis-setenv.sh

Closes #5213 and disables headless tests from Travis-ci

5213 GitHub actions test devel prs

---

.travis.yml
travis-install.sh
travis-script.sh
travis-setenv.sh

Removes sauce tests from Travis-CI matrix

---

.github/workflows/deploySnapshot.yml
prepare-maven.py

5229 snapshots on GitHub actions

---

travis-after-success.sh

Removes mongo-log from builds as it is already taken off from code

Removes mongo-log from builds

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/index.ts
muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

Guider with students who has protection order in place

---

muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/WorkspaceHtmlMaterial.java
muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/evaluation/EvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/wcag/course/CourseAT.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/wcag/records/RecordsAT.java
muikku-atests/src/test/resources/sql/workspace1EvaluatedMaterialSetup.sql
muikku-atests/src/test/resources/sql/workspace1ExerciseMaterialSetup.sql
muikku-atests/src/test/resources/sql/workspace1Material2Setup.sql
muikku-atests/src/test/resources/sql/workspace1MaterialSetup.sql
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/material/model/HtmlMaterial.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/HtmlMaterialController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/dao/HtmlMaterialDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/operations/HtmlMaterialCloneOperation.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/HtmlMaterialRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/HtmlRestMaterial.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/ContentNode.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
updates/1.102/210122_remove_material_revision.xml

Removes revision information from html materials

---

.github/workflows/deploySnapshot.yml
.github/workflows/releaseOrDeploy.yml

Fixing git commit issue with releases

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/users/index.ts
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java

5269 usergroups are displayed in double

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/aside.tsx

removes records info from inactive student

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/HtmlMaterialFieldChangeListener.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/MaterialFieldCollection.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/QueryConnectFieldController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/QueryFieldChangeListener.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceMaterialConnectFieldAnswerDAO.java

- resolves #3654
- resolves #5277

Connect field update support

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java

Changes to determining if courses have an evaluation fee or not

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
pom.xml

- Fixes couple of test packages that failed on sauce
- parent pom had weird tag in scm connection
- removes duplicate test from CourseTestsBase

test fixes and pom tag

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAutoReplyController.java

Automated vacation message category

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java

Fixes NPE in TOR when students' credit has no grade

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/link.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/selectable-list.tsx

accessibility support to selectable list

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java

wait for ckeditor before reading it's contents

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/StudentGroupMembersPayload.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupController.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

- add members to student groups
- remove members from student groups
- resolves #5327

End-points for student group members management

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar.tsx

Locale fixes for search fields

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SchoolDataSearchReindexListener.java

Fix for reindexing entities with task=ALL

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/management/CourseMaterialsManagementTestsBase.java

Assignment type change test

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/videos.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/carousel.scss

pure carousel

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx

Restores the communicator search behaviour
Couldn't find any issue to relate to this branch, so it has no number nor fixes.

Restore communicator search behaviour

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemCourseAssessmentRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemTemplateRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistSummaryItemRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java

Worklist backend support

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemRestModel.java

Minor datatype changes to worklist items

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemTemplateRestModel.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

More fine-grained implementation of worklist item editability

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx

Bind missing on class method

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/form-element.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx

Adds delay to search form element and removes it from the parent element

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application.tsx

search respects filters

---

.github/workflows/deploySnapshot.yml

Shoots a webhook to staging after devel deployment is done

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java

Communicator recipient role check bug fix

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemTemplateRestModel.java

- added billing number to worklist item and template
- resolves #5418

Worklist customer changes (billing number)

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/announcer/CourseAnnouncerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/management/CourseMaterialsManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/evaluation/EvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/user/UserTestsBase.java
muikku-atests/src/test/resources/muikku-data/test/test-roles.sql

Closes #5426 
Also tests student sending communicator message to teacher

Fixes teacher role not working in tests

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java

Fixes #5443

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java

5445 communicator reply test

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/dialogs/deactivate-reactivate-user.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/pager.scss

5300 paging for workspace users

---

muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/pom.xml
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/indexpage/IndexPageTestsBase.java

Get user id from test rest rather than using straight jdbc connection.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss

Closes #5452 
gives staffmembers container height only if there's paging

content align fix for staffmembers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/edit-usergroup.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/new-usergroup.tsx

+ Some code cleaning from unneeded code
Closes #5429

Remove users from user group dialogs summaries

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/dialogs/new-edit-journal.tsx

Max length for journal title set to 255 chars.
- new-edit-journal-tsx
Resolves #5107

Max length for journal title set to 255 chars

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx

Small improvements in the loading of user lists
Fixes #5450

Fixes the refresh bug from workspace users

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistItemStateChangeRestModel.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Worklist item state and batch update support

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/dialogs/new-edit-journal.tsx

- Existing unsaved journal draft can now be cleared
- Instruction page has again correct title
Resolves #5468 & #5481

5468 cannot clear journal draft when continuing existing new journal draft

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java

- Fixes discussionAdminCreateAreaTest instability
- Removes dum dum catch clause in test which was thus avoiding actual
testing.

Discussion test fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/image.tsx

Handle invalid images coming from raw html

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/payload/WorklistApproverRestModel.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/LocaleLoadListener.java
muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/worklist/WorklistRestMessages_en.properties
muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/worklist/WorklistRestMessages_fi.properties
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Email notification when a teacher submits their worklist for approval

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/user-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/user.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students.tsx

Creates a "User" component
Closes #5496

User component created and placed in the user panel

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-threads.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/threads/threads.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx

- Avatar component is use everywhere where avatar is needed
- contains some minor changes and code cleaning
- current-thread.tsx
- discussion-threads.tsx
- threads.tsx
- avatar.tsx
- summary.tsx
Resolves #3845

404 error from loading avatar is fixed:

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx

Small optimizations to the drag and drop functionality which should allow it to work in a more efficient way and avoid issues with rendering and it being wonky.
Fixes #5050 to a degree, it is still linked to speed.
Also with devtools drag and drop might work differently.

Drag and drop optimization

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx

Null check on drag

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/mathjax-react-loader/index.tsx

5555 - Removed single dollar delimiter support from MathJax

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx

For everyone else than students
Closes #5544

Toggle unpublished workspaces in coursepicker

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/work-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-sub-panel.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfileJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfileJsPluginMessages_fi.properties

Resolves #5535 
* Adds option for the teachers to submit current months entries for approval
* Adds total row that calculates section's entries inputted values together (price * factor)
* Mobile fixes for worklist entries

5535 - Yhteensä-rivi työlistamerkintöihin 

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-base.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/current-thread.tsx

Workspace TEACHER, ADMINISTRATOR, MANAGER, STUDY PROGRAMME LEADER are
allowed to remove any message in workspace forum
Closes #4961

Workspace discussion ui permissions to delete a threads

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationManagementWorkspaceRESTService.java

Changes the access so that organization workspace list shows all the
workspaces
Fixes #5531

Organization workspace listing change

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java

Fix for WorkspaceUserEntity not always keeping in sync with Pyramus

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/TestUtilities.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/CourseBuilder.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/picker/CoursePickerTestsBase.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java

- resolves #5540
- requires Pyramus issue 1257

Optimized workspace entity creation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/user-index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss

Resolves #5557
Increases journal's students maxResults to 500 so enough students will be fetched from REST to be matched with Journal's creators. 
This is a bandaid fix and Journal needs to be redesigned from the scratch in the future.

5557-journal-show-all-avatars-missing

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/OrganizationStudentsActivityRESTModel.java

Organization overview active/inactive students

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts

Creating or pasting page now correctly places it right position
Resolves #5534

Creating or pasting page now correctly places it right position

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationManagementWorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/model/OrganizationOverviewWorkspaces.java

Organization overview for workspaces

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/WorkspaceForumRESTService.java

Fix for forum statistics NPE

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts

Fix for workspace list

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/OrganizationContactPerson.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/OrganizationContactPersonType.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Organization overview - contact person

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx

- Sorter-fields now correctly shows wrong and correct answers when checking
answers
Resolves #5566

Sorter-field updates now correctly:

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationManagementWorkspaceRESTService.java

Fixes searching for course templates only in organization workspace management

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/MatriculationEligibilities.java

Related https://github.com/otavanopisto/pyramus/pull/1271

Added compulsoryEducation to MatriculationEligibilities

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAutoReplyController.java

Less logging when vacation auto reply isn't sent

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/WorklistController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/chat-settings.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/work-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/status.ts
muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
muikku/src/main/webapp/WEB-INF/templates/base.xhtml
updates/1.106/210614_chat_worklist_pluginsetting.xml

If you are from an another organization and your role privileges are below an administrator: 
-Removes worklist and chat settings from profile view
-If you navigate to chat / work list url's in profile, will show an empty view 
-Removes chat bubble from environment views
-Removes chat settings from workspace settings
-Removes chat bubble from workspace views
Closes #5606

5606 disable chat

---

updates/1.107/210618_workspaceuserentity_index.xml

Performance index to WorkspaceUserEntity table

---

matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationRESTService.java
matriculation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/restmodel/MatriculationExamAttendance.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/MatriculationExamAttendance.java

Related to https://github.com/otavanopisto/pyramus/pull/1279

Passthrough for MatriculationExamAttendance funding

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/workspace/WorkspaceRestMessages_en.properties
muikku-rest/src/main/resources/fi/otavanopisto/muikku/rest/workspace/WorkspaceRestMessages_fi.properties

Added student's studyprogramme to message caption. (course signup/communicator)

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx

Fixes #5185
Needs testing, I couldn't make openfire work yet; but the fix is simple enough.
I'd comment if I manage to get openfire to work.

prevent joining private chat with oneself

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dropdown.tsx

Fixes #5633 5633
I assume it does, technically merging this would do no harm, it is just a slight memory leak that could occur in very specific circumstances.

checked unmounting status

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/users/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/form-element.tsx
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/organization/OrganizationJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/organization/OrganizationJsPluginMessages_fi.properties

Also fixes a bug where SSN wasn't saved.
Closes #5607

Adds correct error messages to user creation errors.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/aside.tsx

Fixes coursepicker bug

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dropdown.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

Fixes #5172 
Makes announcements usergroups only load when viewed.

5172 load announcement usergroups only when selected

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx

Fixes the broken source

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/user-index.ts
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/UserWhoAmIInfo.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
updates/1.108/210824_defaultorganization.xml

isDefaultOrganization variable to whoami endpoint

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces/workspace.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/organization/OrganizationJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/organization/OrganizationJsPluginMessages_fi.properties

Adds link to workspace and some style changes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/aside.tsx

from those who have only 1 organization
Closes #5694

Removes organization filter

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java

Fixes organization management contact person 403

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Workspace listings return 204 instead of 200 empty list

---

muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Added correct audio icon which are used with CKE custom styles

---

muikku-core/src/main/java/fi/otavanopisto/muikku/session/local/LocalSessionControllerImpl.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/util/OrganizationalEntity.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/workspace/WorkspaceEntity.java

Limit other organizations' workspace activity for roles lesser than admin

---

muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/local/LocalSessionControllerImpl.java

Allow cross-organization access to students and custom roles

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java

Requires https://github.com/otavanopisto/pyramus/pull/1298

Pyramus signup group change compliance

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/user-index.ts
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/UserWhoAmIInfo.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

- resolves #5722
- resolves #5726
- resolves #5727

Better backend support for handling roles and permissions in the UI

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/OrganizationStudentsActivityRESTModel.java

Improved student summary endpoint performance

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/image.tsx

Fixed issue where empty src attribute within img could crash the whole view

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/index.tsx

Makes scripts not be requested to load twice in certain scenarios, not relying on cache.
Fixes #5751 maybe?...

Optimized script loading

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/users/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/edit-staff.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/users/index.ts

Fixes for the organization layer bugs

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-event-content-card.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/evaluation.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss

5807 literal feedback styles

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/shared.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/usergroups.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/usergroups/usergroup.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces/workspace.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useInfinityScroll.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/ref-wrapper.scss

5770 tab infinity scroll

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/ckeditor.ts

CKEditor rollback to 4.12.1

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/shared.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/audio-field/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/base/synchronizer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/file-field/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/math-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/multiselect-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/organizer-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx

5823 taskfield persistent saved indicator

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java

price into evaluation test

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/application/workspaces/workspace.tsx

Fixes the draggable bug in swiper slides

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/footer.tsx

* Privacy policy links update

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx

5767 sorter field linebreak fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/color-picker.scss

Fixed color-picker's zindex issue

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/profile.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/general-information.tsx
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

5842 profile dates fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-sub-panel.scss

Added nowrap for worklist entries description so they wont break line

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/content-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/navbar.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/zoom.scss

Fixes zoomed image's stack order with navbar

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students/student.tsx

Fixes a guider bug for how studies ending is shown

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/teachers.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-sub-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/glyph.scss

Non active student should not see course teachers

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/TestUtilities.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java

Resolves some issues in GuiderTest and adds a studyendtime warning test

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message-editor/answer-message-drawer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/assignment-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/excercise-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/supplementation-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/chat-settings.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/contact-information.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/security.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/vacation-settings.tsx

Prevented multiple clicks when sending messages in communicator. Added disabled props to buttons during send process is happening
Resolves #5837

Prevented multiple clicks when sending messages in communicator

---

muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Workspace evaluation fees as a meta tag

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/profile/ProfileBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsBackingBean.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/general-information.tsx
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

5907 studytime dates

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java

Workspace activity for teachers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/workspace/evaluation-request-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses/course.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/dialogs/workspace-signup.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts

- all data fetching related to feeInfo has been replaced with
meta tag data
Resolves: #5903

5903 changes:

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx

Latest messages count raised from 6 to 10
Resolves: #5516

Latest messages count raised from 6 to 10

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/UserIndexer.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NeverLoggedInNotificationStrategy.java

Elastic class cast fix for crashing notifications

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/entries/workspace.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/base-main-function.ts

Non-loggedin users could not see certain icons in workspace navbar

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java

Test for sending message from guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx

Default page for workspace user's stafflist pager has been fixed
Resolves: #5929

Workspace users stafflist pager default page fix

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Return hidden workspace users in endpoints related to basic workspace functionality

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation-list/evaluation-card.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss

Evaluation request delete is only possible in request list and archiving only workspace list
Resolves #5940

5940 arviointipyyntoa ei voi poistaa

---

muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Changes user group query to separate terms into individual must queries

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message-editor/answer-message-drawer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx

Default maxResults for recipient fetching for Input contact autofillcomponent increased from 10 to 20.
Resolves: #5948

5948 - Contact autofillcomponent increased from 10 to 20

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/index.ts

Added ToR workspaces endpoint that includes unpublished workspaces

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/application-panel/application-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/tabs.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useIsAtBreakpoint.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useIsMobileWidth.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/_exports.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/exports.d.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/webpack.config.js

Tabien mobiilin ja desktopin eriyttäminen

---

muikku-atests-plugin-rest-model/pom.xml
muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/CeeposPaymentConfirmationRestModel.java
muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/CeeposPaymentResponseRestModel.java
muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractIntegrationTest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/TestUtilities.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/announcer/AnnouncerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/resources/muikku-data/test/test-data.sql
muikku-atests/src/test/resources/muikku-data/test/test-roles.sql

Study time Ceepos testing

---

muikku-core-plugins/pom.xml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/.stylelintrc.json

Frontend-maven-plugin update

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java

Fix for removing assessment requests

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRESTService.java

More accurate Ceepos payment response validation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/iframe.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/webpack.config.js

Closes #6002 
* Changes package.json install script path of webpack so it works with Windows also. 
* Fixes z-index of material page synchronizer so it will appear on top of ToC if necessary
* Updates devDependency packages
* Fixes TypeChecker package so it will always be present wheter compile is dev or prod.

6002 saving notification z index

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/_exports.scss

Typo fixed

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/cache/AbstractEntityCache.java

System property for logging entity cache statistics

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar/labels.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dropdown.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/form-elements.scss

Changes:
- overlfow issue with flags and labels is now fixed. Added overflow property.
- fixed also small bug with flags in the guider that prevented using arrow keys to navigate between items
Resolves: #5986

Labels and flag overflow bug fixed

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java

If both a student and a workspace have curriculums defined, allow signing up only if student's curriculum is amongst the curriculums of the workspace. If neither object has curriculums defined, carry on as usual.
- resolves #5950

Curriculum check when determining whether a student can sign up to a workspace

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java

webhooks after stubbing

---

muikku-atests-plugin/pom.xml
muikku-atests/pom.xml
muikku-bom/pom.xml
muikku/pom.xml
pom.xml

Removed references to deprecated evaluation projects

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx

* Adjusted CKE ACF  rules

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderPermissions.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/StudentContactLogEntryCommentRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/StudentContactLogEntryRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/StudentContactLogEntryType.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Yhteydenottotiedot ohjaamoon

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-textfield/plugin.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json

6005 materials textfield autogrow

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/state-of-studies.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts

Muuttaa nimeämisiä ohjaamon staten osalta ja tekee latausanimaatiosta järkevämmän, sekä korjaa muutamia bugeja
Closes #6088

6088 guider currentstate vs state

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/study-history.tsx

adds loader to study history tab

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/iframe.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/outside-click-listener.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/click-outside-listener.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss

Iframe scrolling bug fixed by wrapping it with custom component that
handles outside component click with given onClick props. This fix is only
affecting mobile/pad device sizes
Resolves: #6100
Resolves: #3072

6100-iframe bug fixed:

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java

Fixes an issue in UI where coursesCompleted is shown when status is ELIGIBLE although it would always be zero.

Return credit count even when eligible

---

muikku-core/src/main/java/fi/otavanopisto/muikku/rest/StudentContactLogEntryCommentRestModel.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/StudentContactLogEntryRestModel.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

* Included field hasImage to StudentContactLogEntryRestModel &

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java

Filter support to list only students' active/inactive workspaces in Guider

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/WorkspaceIndexer.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/IndexedWorkspace.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Added missing begin and end date fields to indexed workspaces

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/index.ts

Records loading fixed
Resolves: #6133

Records loading fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx

* Added back study activity indocators for student in courses materials view

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationResourcePermissionCollection.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/rest/model/WorkspaceGradingScale.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/evaluation.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/CompositeGradingScale.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusCompositeGradingScale.java

Bug when using unknown grade system that caused ui to crash is fixed. Unknown grade system is now added to other options if needed
Resolves: #6118

6118 editing an existing workspace evaluation with an unknown grade crashes the UI

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx

- resolves #6140 
- requires Pyramus issue 1385

Yhdistelmäopintojen moduulihinta samalle oppiaineelle

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/CommunicatorMessageIndexer.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/IndexedCommunicatorMessageRecipient.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Faster indexing for markasread

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts

Activity indicators are again back in action for everyone and not only for student. Only requirements is that you are signup user

Fix show activity balls

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/aside.tsx
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_fi.properties
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java

- More specific message if no student is available for guider/teacher
- Filtering headers are also removed if that specific filters are no available
Resolves: #6147

6147 guider crash

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/base/synchronizer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss

- Syncronizer message moved below of material fields
Resolves: #6153

Syncronizer message moved below of material fields

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-planning-tool.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/state-of-studies.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss

- visibility bug fixed
- mandatory course calculation fixed
Resolves: #6165

Hops visibility and mandatory calculation bug fixed

---

muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordPluginMessages_fi.properties

More descriptive credential mail content

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketMessenger.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/SchoolDataPyramusPluginDescriptor.java

- resolves #6178
- resolves #6179

Disable Pyramus scheduler and log less about websocket close failures

---

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NeverLoggedInNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoLoggedInForTwoMonthsNotificationStrategy.java

Fixes for notifiers not processing all users

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/evaluation.scss

Modal width fixed
Resolves: #6190

evaluation modal width fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel/hooks/use-course-carousel.tsx

Alternative options added to coursel carousel content loading procedur.
Resolves: #6195

Alternative options added to carousel

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-course-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-course-table.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-suggested-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dialog.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/hops.scss

Following improvents done. Content overflows nicely, course names and suggestion buttons are on their separated rows etc. Includes scss changes.
Resolves: #6193

suggestion list style improvments

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumThreadNewMessageNotification.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumThreadSubsciptionController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumThreadSubscriptionNotifier.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/events/ForumThreadMessageSent.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/wall/ForumThreadSubscriptionDAO.java
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumPluginMessages_fi.properties
muikku-forum-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumThreadSubscriptionRESTModel.java

Keskustelualueen herätteet

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java

REST error message logging

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/assignment-editor.tsx

Extra evaluation grades removed
Resolves: #6202

Extra evaluation grades removed

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NoteRestModel.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/dao/NoteDAO.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-edit.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-new.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/notes.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_fi.properties
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java

- all notes are shown without date restrictions
- notes are not moved to archived pool without users evaluation.
- notes item have now expired indicator
- datepicker limits added, so now wierd date compination can't be made
Resolves #6204 
Resolves #6205

6204 notes dates shenanigans

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java

If "raised" grade is failed, show it as such in evaluation history

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/shared.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/file-uploader.scss

isStringHtml bug fixed

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/disconnect-warning.tsx

dialog overlay click disabled
Resolves: #6217

dialog overlay click disabled

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json

* 10 vulnerabilities fixed in NPM packages

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/print.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/util/base.scss

Closes #5864 
This PR only solves couple of printing issues regarding overlapping elements and unnecessary paddings.
We could design better printing rules later on.

* First iteration of print styles

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/assignment-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/dialogs/evaluate.tsx

Workspace evaluation and assignment evaluation grade and gradesystem bug fixed
Resolves: #6234

Grade systems bug fixed... presumably

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chatMessage.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/groupchat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/privateChat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/hops.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/chat.scss

Closes #6239 
Also fixes one HOPS phase related issue

6239 chat fixes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceSignupScheduler.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Fixes the issue with timing of sign up end

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts

Signature fixed
Resolves: #6251

Signature fix

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/model/MockStaffMember.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java

Tests for staff study programmes in Guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx

6280 poistetaan omat ohjaajat toistaiseksi

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/privateChat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/chat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/browser-tab-notification.ts
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/chat/ChatJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/chat/ChatJsPluginMessages_fi.properties

6278 tabi vilkkumaan uuden viestin saapuessa

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/material/model/MaterialViewRestrict.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/content-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx

Material section and page view restrictions improvments and bugs resolved.
Resolves: #6289

6289 osion nakyvyyden rajaaminen

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/material.tsx

Buttons are now hidden
Resolves: #6296

Buttons are now hidden

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/HopsController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NotificationController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupGuidanceController.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/MeRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/AssessmentRequestNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NeverLoggedInNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoLoggedInForTwoMonthsNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoPassedCoursesNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/RequestedAssessmentSupplementationsNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java

6298 opintoohjaajien listaaminen

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java

Fixes #6318

---

muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceUserSignupDAO.java

Automatic messages tests

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/announcements-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/latest-messages-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/wall-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/workspaces-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/empty.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_fi.properties

changes locales for the wall tasks

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss

5752 kurssin kayttajat mobileonly tabs

---

muikku-atests/pom.xml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/toc.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/toc.scss
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
muikku-pyramus-oauth/pom.xml
muikku-school-data-pyramus/pom.xml

Material table of content improvments. Added hideable sections including open/close all sections buttons. Toc sections also have active indicator if it contains current active material.
Resolves: #6361 
Resolves: #6360

6361 sisallysluettelon suodattaminen

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/MaterialFieldCollection.java

Fix for HTML entities breaking material saving

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Workspace publicity bug fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/chat.scss

Ongelma toistui toisinaan ja toisinaan ei, mitään suoranaista syytä ei openfiresta löytynyt, joten oletus on, että vika on muikun päässä.
Ainut mahdollinen syy, minkä ilman debuggauksen mahdollisuutta löysin, oli se, että olemassaolevien chatikkunoiden lataaminen ei ollut async. Laitoin sen asynciksi. Mitään haittaa siitä ei pitäisi olla, että odotetaan vastaus-stanza valmiiksi.
Ominaisuus toimiikin muutoksen jälkeen normaalisti käyttäjälle. Siivosin piiloon myös turhat roster-lataukset.
Closes #6395

6395 offline tilassa oleva ohjaaja ei saa chat viestiä

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/dao/InterimEvaluationRequestDAO.java

- fixes #6412
- couple of deprecated constructor fixes

Evaluation crash fix when staff member has no workspaces

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts

Fixes Could not load workspace error when not logged in

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJournalController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceJournalEntryDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/editors/workspace-journal-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/environment-dialog.scss

Oppimispäiväkirja: Tehtävänä oppimispäiväkirjamerkinnän otsikko on aina kyseisen sivun otsikko

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialFieldAnswerController.java

Error logging when retrieving a text field answer fails

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java

Ohjaamo: Korjaus yhteydenottomerkinnän muokkaamiseen

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java

Elastic crash fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts

- fixed a bug that prevented opening a message when multiple messages were selected and toggleAllMessages was on
Resolves: #6445

6445-Changes:

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/aside.tsx

Only active students are now listed in journal navigation
Resolves: #6423

Only active students are now listed in journal navigation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/evaluation.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss

- journal assignment default height is same as other assignment fields
- evaluation journal list can now be sorted by date. Default is ascending
- added sorter button to evaluation journal list with tooltip
Resolves: #6441

6441 oppimispaivakirjatehtava pikkufikseja

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/signature-update.tsx

Temporary fix. Root problem will be fixed when upcoming ckeditor fix is merged and this should also probably fix these kind of problems for the future.
Resolves: #6430

Temporary fix before ckeditor upcoming fix is merged

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/shared.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-period-plan.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/hops-steps/hops-studies-planning.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/hops-compulsory-education-wizard/text-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/table.scss

- added new temporary functionality to create study plan for 6 month period
Resolves: #6391

Hops form study plan:

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/journal-feedback-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/assignments-and-diaries.tsx

* Fixed wrong classNames

---

muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/DiscussionMessage.java
muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/DiscussionThreadReply.java
muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java

also
- Better forum reply test
- Forum post test for student
- Some helpers for future testing
- Closes #6369

** Forum subscription test.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceUsers/users.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss

6376 change mobileonly tabs

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/toc.scss

Toc dropdown box is fixed. It is now only shown if topic contains no pages.
Resolves: #6490

Toc dropdown box fix

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Korjattu opiskelijan aktiivisuustila jos päättymispäivä on tulevaisuudessa

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java

Fixes the bug with multiple assessment requests for the same workspace and student

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/evaluation.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/external-content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/interim-evaluation-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-assignment.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/evaluation.scss

Lang attribute crashing fixed.
Resolves: #6507

Lang attribute crashing fixed.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record/journal.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journals-list-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss

* Added mandatory and normal journal entry visualization

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/toc.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/toc.scss

* Fixed workspace guides toc__header layout

---

pom.xml

Use maven-install-plugin 2.5.2

---

pom.xml

Defines latest working version, for us, of maven-deploy-plugin

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/.prettierrc.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/websocket.ts

Remove 404 answers from websocket ticket validation

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Lang attribute to the copied workspace

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/workspace/navbar.tsx

Possible fix for screen reader with request evaluation button in navbar
Resolves: #6408

6408-pyyda-arviointia-ja-ruudunlukuohjelma

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/TestUtilities.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/model/MockCourseStudent.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseAccessTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/announcer/CourseAnnouncerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/journal/CourseJournalPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/management/CourseManagementTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/flags/FlagTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/indexpage/IndexPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java

Puts course into mockcoursestudent in tests

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record/material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/records-group/records-group-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/records-indicators/activity-indicator.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss

6559 studies records view data duplication and other issues

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application.tsx

Student diary select no more includes inactive student
Resolves: #6567

Student diary select no more includes inactive student

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

adds name extension to the latest workspaces

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumSubscriptionNotifier.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/events/ForumMessageSent.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/WorkspaceForumRESTService.java

keskustelualueen herätteessä väärä viesti

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumSubscriptionNotifier.java

Työtilan tilatun keskustelualueen ja viestiketjun herätteen url

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/draggable.tsx

Fixes following issues:
- Failed grades in evaluated assignments now prevents any further edits to that assignment
- Draggable component drop timer adjusted so it reacts faster to drop events
Resolves: #6580 #6583

6580 arvioitujen tehtavien muokkaus

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/notebook/notebook.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/popper.scss

Selected note position falsy value checks are now better. Popover font fixed also
Resolves: #6590

6590 notebook new note position bug fix

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java

Journal exercise test

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationNotificationController.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/matriculationExaminationWizard/matriculation-examination-enrollment-completed.tsx

Updated matriculation texts

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx

* Adjusted date and time display within the communicator messages

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java

Fix for course tutors and organizers potentially showing up in course's teacher list

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/hooks/usePedagogy.ts

console log removed
Resolves: #6606

console log removed

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/readspeaker.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/locale.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/workspace/WorkspaceLanguage.java

Language codes are fixed.
Resolves: #6609

6609-Language codes are fixed

---

muikku-core-plugins/pom.xml
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SchoolDataSearchReindexListener.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchReindexEvent.java

Reindex study programmes (from Pyramus)

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatController.java
updates/1.137/230801-chat.xml

Master availability flag for chat

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatSyncController.java

Disable chat synchronization features if chat is disabled

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java

Tests signature feature in communicator

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/math-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/mathjax.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/tsconfig.json

6627 mathfield html entities

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Fix for filenames messing up URLs

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/.eslintignore
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/.gitignore
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/.prettierignore
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/.stylelintignore
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/generator-config.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/openapitools.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

OpenApi swagger yaml added to recources folder and it has already base for api spec done, but it need more testing. Openapi-generator set to be ready for api generations.
Resolves: #6635

6635 swagger openapi spec to muikku and openapi generator

---

muikku-core/src/main/java/fi/otavanopisto/muikku/users/LastWorkspace.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java

Viimeisimmät kurssit refaktorointi

---

muikku-core-plugins/pom.xml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcements/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcement-view.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/dialogs/delete-announcement.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/dialogs/new-edit-announcement.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/announcements-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHome/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/announcements/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Announcements side of muikku is converted to use new MApi created by using openapi-generator and OpenApi swagger.yaml document. No additional logic refactoring done, just api fetches changed
Resolves: #6637

6637 announcement openapi generator rework

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/context/readspeaker-context.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/progressData.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

* Fixes for the sluggish material editor

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java

- these usually get "stuck" in github actions testing

** Fix for couple of tests

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/aside.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/label-update.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/latest-messages-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Communicator api refactor done. Added also MApiError type guards to api folder. 
Resolves: #6643

6643 communicator openapi generator rework

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/announcements/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

Enviromental level announcement are not anymore loaded in workspace
Resolves: #6661

Enviromental level announcement are not anymore loaded in workspace

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java

Corrected guider link in course signup

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/workspace/WorkspaceRoleArchetype.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusIdentifierMapper.java
updates/1.139/230925-workspace-roles.xml

Workspace tutor and organizer support

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/general-information.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

fixes a locale bug

---

muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

* isCourseMember now functions correctly

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/worklist/rest/WorklistRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/evaluation.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/profile.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-editable.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-row.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-section.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/work-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/dialogs/delete-worklist-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/dialogs/submit-worklist-items.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/profile.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Worklist paths refactored to use newly generated api
Resolves: #6709

6709 worklist openapi generator rework

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/pedagogy/rest/PedagogyRestService.java

Pedagogisen tuen suunnitelman näkyvyys

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/dao/ForumMessageDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/dao/ForumThreadReplyDAO.java

Save last modification when deleting forum messages and threads

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/contacts.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/credentials.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/locales.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/forgot-password-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/chat/chat.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/credentials/body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/credentials/body/return-credentials.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/contacts.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/credentials.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/locales.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Some minor set of paths refactored to use newly generated api:
- forgotpassword
- me
Resolves: #6714

6714 other minor m api path openapi generator rework

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Recipient id removed and replaced with userEntityId
Resolves: #6729

Recipient id removed and replaced with userEntityId

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/model/CeeposProductType.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/CeeposController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/purchases.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

- locale changes
- resolves #6728

Oppilaitostiedosta riippuvat arviointimaksut

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx

Fixes the course description field

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/avatar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/avatar.scss

Avatar refactore to use img tag
Resolves: #6747

Avatar refactore to use img tag

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/notes.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/helpers/filters.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/hooks/useNotesItems.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-edit.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-new.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/wall-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/wall/note.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/useNotes.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Notes paths refactored to use newly generated api
Resolves: #6736

Notes api path rework done

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/activitylog/rest/ActivityLogRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/records/summary.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/api/api.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/graph/main-chart.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/workspaces/workspace/workspace-chart.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/guider/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/summary.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/ISO8601UTCTimestamp.java

Activity logs paths refactored to use newly generated api. Contains also backend changes to previously mentioned paths date type parameter format.
Resolves: #6735

6735 activity logs openapi generator rework

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
muikku-atests/src/test/resources/muikku-data/test/test-data.sql

** Fix for bugging evaluation test

---

muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

- ...and some pointless, minor optimization at that

Fix for guider crashing with some students

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/feed/FeedSynchronizer.java

Client was not closed and when it was finally free'd by system it printed a warning.

Fixed issue where client is left hanging and garbage collected

---

muikku/src/main/webapp/WEB-INF/web.xml

It printed a warning at startup.

Removed deprecated context-param

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/users/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/user-index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts

Removed old commented "if else" style reducers blocks that were left after reducer refactor
Resolves: #6692

Removed old commented "if else" style reducers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts

Evaluation workspace max result pump up to 500
Resolves: #6766

Evaluation workspace max result pump up to 500

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/help-material-page.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx

Workspace help materials now can use Readspeaker component
Resolves: #6686

Workspace help materials now can use Readspeaker component

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

Forced discussion reload when using back button after creating new discussion message entry
Resolves: #6750

Force reload for workspace discussion threads

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx

Reply all added back to message functionalities
Resolves: #6855

Reply all functionality back in action

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journal-comment-list-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

* Fixed workspace additional info nullable date

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts

* Fixed wrong attachment id when loading material attachments

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Fixes asking for confirmation when updating/deleting material pages with answers

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-comment.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/assignments-and-diaries.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record/journal.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/current-record/journalComment.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journals-list-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/evaluation.scss

* Adjusted and unified date & time formatting

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies/ceepos.tsx

Allow admins to remove ongoing Ceepos orders

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss

Fixed tabs container not visible between 769 px and 1023 px

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx

Dialog does not prevent scrolling anymore after closing it
Resolves: #6935

Dialog does not prevent scrolling anymore after closing it

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/easy-to-use-reading-functions/reading-ruler/reading-ruler-base.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/reading-ruler.scss

Users have fully control of reading ruler alpha value
Resolves: #6884

Users have fully control of reading ruler alpha value

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/users/test/UserRESTServiceTestsIT.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/User.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

Removed unused properties and an unused endpoint.
Check that these are truly unused - they seem so to me.

Cleanup of unused properties in User model

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/assignments-and-diaries/assignments-and-diaries.tsx

Spelling mistake fixed that did prevent loading exercise assignments
Resolves: #6942

Spelling mistake fixed that did prevent loading exercise assignments

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/HopsController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/SuggestedWorkspaceRestModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel/course-carousel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/carousel/hooks/use-course-carousel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/study-progress/suggestion-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/summary.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/study-matrix.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

LOPS: Bug fix to avoid listing OPS 2016 courses

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/mock/mock-data.ts

MAY 5. -> 15.
MAY 6. -> 16.
Resolves: #6929

MAY courses changed 5 -> 15, 6 -> 16 from uppersecondary OPS2021

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumResourcePermissionCollection.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/discussion/body/application/discussion-current-thread.tsx
updates/1.144/240216-forum-permissions.xml

- fixes a crash when trying to open a course discussion thread
- adds some relevant discussion permissions for study guiders
- removes all environment level discussion subscriptions
- removes environment level discussion

Discussion permission fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/main-function/navbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journal-comment-list-item.tsx

* Removed deprecated environmentForum check from forum permissions

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/study-history.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/chat-settings.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/contact-information.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/general-information.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/security.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/vacation-settings.tsx

6972 layout fixes

---

muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAutoReplyController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorMessageRecipientList.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java

Reject communicator messages without recipients

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumAreaSubsciptionController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumThreadSubsciptionController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/InactiveUserListener.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Remove users' workspace forum subscriptions when they leave the workspace

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Fixes #6977

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

Opintohistoria-lokaalimuutos

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/workspace-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-row.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/profile/body/application/components/work-list-section.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-sub-panel.scss

Fixes rounding with worklist and evaluation prices

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/environment-dialog.tsx

FocusTrap disabled
Resolves: #7003

FocusTrap disabled

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/announcer/AnnouncerPermissionsTestsIT.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncerPermissions.java
updates/1.147/240312-announcer-permissions.xml

Show group announcements to teachers

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/HopsController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceUserEntityDAO.java

Allow workspace teacher to see student curriculum

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/MaterialAttachmentUploadServlet.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceManagementBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java

Prevent Study Guider as Workspace Teacher from editing Workspace

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dialog.scss

Closes #7020 
Enrollment dialogi esti aikaisemmin SIGN IN napin klikkauksen sekä siitä puuttui sulje rasti. Molemmat ongelmat korjattu.

7020 sign up dialog fixes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

- added and adjusted material permission checks

Material permission tuning

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/activity-indicator.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/records-group-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/records-group.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

Studies records list accessibility rework:
- record items have now keyboard support (space + enter will expand/shrink record info)
- record activity indicator is now focusable and opens info when focus is active
- added aria attributes where they are necessary
Resolves: #6833

6833 wcag 1.1.1, 2.1.1 ja 4.1.2.  suoritukset valilehdella on useita saavutettavuusongelmia

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/styles/workspace-material-styles.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss

7057 new ckeditor style boxes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-filters-chip.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list-item.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes-item-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/notes/notes.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

Notes have now better keyboard accessibility:
- aria-labels
- roles
- keyboard functionality to navigate between notes
- Other minor documentation improvments
Resolves: #6829

6829 wcag 1.3.1, 2.1.1 ja 4.1.2.  aktiiviset tehtavat  alueella on useita saavutettavuusongelmia

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/slide-drawer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/environment-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/portal.tsx

- focus trap configuration changed, should now work as expected with multiple dialogs etc...
- changes affects to dialog, slide-drawer and environment-dialog components
- portal component if closeOnEscape is true, will now close portal in order of creation
Resolves: #7048

7048-changes:

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-mathjax/plugin.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/mathjax.ts

Mathjax rollback from 2.7.9 to 2.7.7

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-signup-groups.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management-signup-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

Changes:
- instruction text changes
- placeholder title removed
Resolves: #7067

7067 workspace signup message after testing changes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/math-field.tsx

7086 mathfield classname fiasko

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAutoReplyController.java

Fix for vacation auto-reply dates

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Fix for underscores in file answers on Firefox

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/instagram.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/card.scss

* Changed frontpage IG links

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/rest/ChatRESTService.java

Allow longer nicks

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

Partial fix to #6955 
Virheilmoitus katoaa mutta opinto-ohjaajalle ei listaudu kurssin opiskelijat kurssin arvionnissa vielä.

6955 Opinto-ohjaajalle arvionnissa tulee error

---

muikku-core/src/main/java/fi/otavanopisto/muikku/rest/JacksonConfigurator.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchIndexUpdater.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/ClientPool.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java

This looks like a drop-in replacement but should still be tested a bit more.

Changed deprecated Jackson JSR310Module to JavaTimeModule

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dialog.tsx

Evaluation scrolling issue fixed
Resolves: #7122

Evaluation scrolling issue fixed

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceSettingsRestModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

fixes the external view link

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/html.ts

7114 crash when turning a memo field into a ckeditor field

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guardian_hops/body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/hops/body.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx

- Old title actions refenrences removed
Resolves: #7137

Old title action references removed

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/MatriculationRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/matriculation/restmodel/MatriculationExamEnrollment.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/@types/shared.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/hooks/use-matriculation.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/steps/matriculation-examination-enrollment-summary-new.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/steps/matriculation-examination-student-information.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/MatriculationExamEnrollment.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusMatriculationExamEnrollment.java

Needs changes to the matriculation form and requires https://github.com/otavanopisto/pyramus/pull/1613

Added contactInfoChange field to MatriculationExamEnrollment

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/contact-event.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/contact-events/editors/edit-event.tsx

Fixes locale bugs in contactlog types and dates

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

Täydennyspyyntöfiksi

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/slide-drawer.tsx

PrevenScroll prop added to slide-drawer FocusTrap to fix scroll issues
Resolves: #7122

prevenScroll prop added to slide-drawer to fix scroll issues

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

Added missing assessment request date for supplementation requests

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/students/student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json

* Fixed guider's wrong date localization

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts

* Potential fix for evel. request error

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusCompositeAssessmentRequest.java

Evaluation card fix

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

Prevent duplicate supplementation request cards in evaluation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/confirm-remove-page-with-answers-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/delete-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/points.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/easy-to-use-reading-functions/reading-ruler/reading-ruler.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/editors/assignment-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-assessment-assignment.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/assignment-info-details/helper.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/assignment-info-details/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dropdown.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/portal.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/assignments-and-diaries/material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/table.scss

Closes #7206 
* Also fixes reading ruler and handles assignment points review requests

7206 sivujen poistaminen muikussa ei toimi

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/hooks/use-matriculation.tsx

* Fixed wrong locality value in matriculation form

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/editor-buttonset.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx

Material section and page visibility saving bug fixed
Resolves: #7215

Material section and page visibility saving bug fixed

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/workspace/navbar.tsx

* Arviointipyynnön lähetys mobiililaiteella

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/content.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx

Drag and drop material page and section fixed
Resolves: #7223

Drag and drop material page and section fixxed

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTModels.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityName.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Käyttää nyt samaa kuin findUsers
Closes #7212

Muutettu aktiivisten käyttäjien tunnistamista findUser-metodissa

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/progressData.tsx

* Material progressbar fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/footer.tsx
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Updated privacy policy link in front page and removed GA

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/footer.tsx

* Accessibility statement update

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/state-of-studies.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/study-matrix.ts

* Added check where aborted course won't get COMPLETED modifier

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

Korjattu puuttuneet oppivelvollisuustiedot eri arviointityypeistä

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/tabs/study-progress/components/progress-table.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/study-progress/components/progress-table.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dialog.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/table.scss

* Fixed sticky positioning of course matrix in guider and studies

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java

- removed local curriculum name cache

Curriculum name cache fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/index.tsx

7150 latexin avaaminen nappainkomennolla

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/SaveFieldAnswerWebSocketMessageHandler.java

- resolves #4620
- incoming websocket message was somehow malformatted, impossible to determine how or why
- should this occur in the future, content of such messages is also logged

Improved logging for websocket data deserialization

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/notes/NotesRESTService.java

Opiskelijan muistilapun luonnissa bugi

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/frontpage/body/organization.tsx

adds title for otavia box
simplifies the otavia box links
closes #7266

removes twitter / x

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/field.tsx

* Fixed math field paste behavior

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceJournalEntryRESTModel.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/evaluation/evaluationActions.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/journals.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-journal-event.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-material.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/steps/matriculation-examination-student-information.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/assignments-and-diaries/hooks/useJournals.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/records-history/assignments-and-diaries/journal.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/index.frontpage.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/hooks/usePageTitle.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/evaluation/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/records/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/journals.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Changes:
- evaluation journal assignment entrys uses now MaterialLoader, to render journal page html content
- material page visibility option order and locale fix
Resolves: #7340

7340 evaluation journal assignment rendering refactoring

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/courses/course.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss

7344-bug-fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/content-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/util/base.scss

* Fixed Materials ToC tab misplacement and background glitch

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-material.tsx

Correction to evaluation material. Now assignment type is correctly checked through assignment objects insteand of directly through material object.

Assignment type is now correctly checked from assigment objects

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/connect-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/multiselect-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/organizer-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/sorter-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/text-field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/organizerfield.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/sorterfield.scss

Two main fixes to material-loader:
- custom editor plugin now correctly shows checked answers between refresh now on
- excersise when now correctly checks answers and shows all answers if student wishes so
Resolves: #5627 #7382

Material loader fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dropdown.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/curriculum-config.ts

- probably fix for tooltips freezing between route changes
- Compulsory curriculum util course hour value corrected to 28h/course

Random frontend fixes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java

Tiedotteen latausfiksi
