otavanopisto/muikku

muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss, muikku/src/main/webapp/resources/theme-muikku/sass/muikku-file-field-component.scss
Changed the way muikku-file-field's labels overriding styles are used. Removed !important rules and added evaluation view specific rules instead.
=> Bug 399 uploaded files evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_item.dust, muikku/src/main/webapp/resources/theme-muikku/sass/_discussion.scss
Fixes some margins in threads view
=> Places the discussion sender name in message threads view.

muikku/src/main/webapp/WEB-INF/templates/main-view.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/screen.scss
=> Adds helpdesk badge to right bottom

muikku-atests/pom.xml, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/schedulers/PyramusScheduler.java
Disable Pyramus scheduler while tests are running, fixes #478
=> ** Disable Pyramus scheduler while tests are running

muikku/src/main/webapp/resources/scripts/gui/muikku-field.js
Fixed by emptying correct answer count container and removing correct/example answers whenever exercise evaluation is requested.
=> Fix for #511

muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/ForumController.java
=>  - Removed workspace messages from environment board

muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js
By taking the description from data-attribute to hidden div container
=> Fixes #468 student records not working

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerWorkspace.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepickercourse.dust, muikku-core/src/main/java/fi/muikku/schooldata/entity/Workspace.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusWorkspace.java, muikku/src/main/webapp/resources/theme-muikku/sass/_coursepicker.scss
#777 (board issue)
Adds name extension from pyramus behind the coursepicker course name
Removes the shortened name, since it does not come from pyramus
=> Ftr 777 course name in coursepicker

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/dao/InboxCommunicatorMessageDAO.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Bug 584 communicator sent delete

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java, muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java
Changed the URL name generation to also work with null titles and to fall back on eight random characters if the resulting URL name would be empty.
=> Fix for #671

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
Rearranged text and memo field generation to minimize DOM changes. Seems to have a favourable effect on the loading speed of some materials, at least.
=> Partial fix for #648

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java
Changed URL name generation so that if the name looks like a file name, the unique counter is appended before the file extension rather than the end of the name.
=> Fix for #813

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-upload.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js
Changed empty content types to application/octet-stream
=> Fix for #812

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js, muikku/src/main/webapp/resources/theme-muikku/sass/_dialog.scss
=> Adjusted cancel-evaluation-button styles to match cancellation color

muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/scripts/gui/muikku-field.js, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss
=> Fix for show/hide correct answers issue

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/discussions.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/widgets/workspace-discussion-delete-area.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-discussions.scss
* Fixes #827
* Also added initial support for delete workspace discussion area but it's hidden for now as scripts between environment and workspace are not merged.
=> Workspace "new discussion area" button's styles

muikku-atests/pom.xml, muikku-atests/src/test/java/fi/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
=> Fixing random fails in CourseMaterialsTests

muikku/src/main/webapp/resources/theme-muikku/sass/muikku-file-field-component.scss
=> Bug 567 file upload

muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java
=>  - Removed hyphens from search strings and replaced them with spaces

muikku-core/src/main/java/fi/muikku/controller/EnvironmentSettingsController.java, muikku-core/src/main/java/fi/muikku/controller/SystemSettingsController.java
=> Bug 700 emails sent from wrong domain

muikku/src/main/webapp/resources/scripts/api/api.js
=> ** Added client-side cache into mApi

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> fixes 861 typo

muikku-mongo-log/src/main/java/fi/muikku/plugins/mongolog/MongoLogProvider.java
=> ** Parameterized mongo-log plugin settings

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_create_message.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_replymessage.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_create_area.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_create_message.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_edit_message.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-journal-edit-entry.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-journal-new-entry.dust
=> * Added maxlength attribute to workspace journal, discussion and

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> ** Removed number and letter index from connect field

muikku-atests-plugin/src/main/java/fi/muikku/atests/AcceptanceTestsRESTService.java, muikku-atests/src/test/java/fi/muikku/rest/test/PyramusMocksRest.java, muikku-atests/src/test/java/fi/muikku/rest/users/test/UserRESTServiceTestsIT.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/schooldatalocal/entities/LocalUserImpl.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceEntityController.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/User.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceEntityDAO.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusUser.java
=> Ftr 531 non relevant users

muikku-rest/src/main/java/fi/muikku/rest/SystemRESTService.java
=> ** Added status page that reponds with "ok" when the application is up

muikku/src/main/webapp/resources/theme-muikku/sass/_mainfunctions.scss
=> Adds a background color #eee for textfield in new message creation

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-base-template.xhtml, muikku/src/main/webapp/WEB-INF/templates/main-view.xhtml
=> Helpdesk info to workspaces

muikku-core-plugins/src/main/java/fi/muikku/plugins/websocket/WebSocketRESTService.java
=> ** Removed websocket ip filter

.travis.yml, muikku-atests/pom.xml
EI tartte mergee ainakaan vielä.
=> Bug 939 saucetests bugging

muikku-developer-tools/pom.xml, muikku-developer-tools/src/main/java/fi/muikku/developertools/rewrite/PackageNotFilter.java, muikku-developer-tools/src/main/java/fi/muikku/developertools/rewrite/WebLibFolderFinder.java, muikku-developer-tools/src/main/java/fi/muikku/developertools/rewrite/WebLibFolderRewriteRules.java, muikku-developer-tools/src/main/resources/META-INF/beans.xml, muikku/pom.xml, pom.xml
=> ** Added a developer tools project

muikku-core/src/main/java/fi/muikku/schooldata/UserSchoolDataController.java, muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataUserGroupListener.java, muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataUserListener.java, muikku-core/src/main/java/fi/muikku/users/UserEntityController.java, muikku-core/src/main/java/fi/muikku/users/UserGroupEntityController.java, muikku-core/src/main/java/fi/muikku/users/UserSchoolDataIdentifierController.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserGroupEntityDAO.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserGroupUserEntityDAO.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserSchoolDataIdentifierDAO.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java, muikku-persistence/src/main/java/fi/muikku/model/users/UserSchoolDataIdentifier.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java, updates/1.0080/151226-useridentifierarchived.xml
=> Bug 951 workspace user archival

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-file-field-component.js, muikku/src/main/webapp/resources/scripts/gui/muikku-field.js, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/muikku-file-field-component.scss
=> Ftr 926 file field saving indicator by adding loaded / total kB info

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Unified material titles shown in the evaluation tool

muikku/src/main/webapp/resources/scripts/gui/muikku-field.js, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss
=> Linebreak support for example answers

muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataUserListener.java
=> School data user discovery environment role NPE fix

muikku-atests/src/test/java/fi/muikku/ui/chrome/course/materials/CourseMaterialsPageTestsIT.java, muikku-atests/src/test/java/fi/muikku/ui/sauce/course/materials/CourseMaterialsPageTestsIT.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core/src/main/java/fi/muikku/session/RestSessionControllerImpl.java, muikku-core/src/main/java/fi/muikku/session/SessionController.java, muikku-core/src/main/java/fi/muikku/session/SessionControllerDelegateImpl.java, muikku-core/src/main/java/fi/muikku/session/local/LocalSessionControllerImpl.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java
=> Bug 1008 unarchive workspace student

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/UserPyramusClient.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/EntityCacheEvictor.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/SystemEntityCache.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/UserEntityCache.java
=> Changed UserEntityCache to be plain CDI bean instead of EJB bean

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/SystemPyramusClient.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/UserPyramusClient.java
=> Removed manual cache evicts from Pyramus REST cache

muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/AssessmentRequestController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/CommunicatorAssessmentRequestController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialUploadBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceController.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceSchoolDataBridge.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceSchoolDataController.java, muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
=> Plenty of bug fixes to searching and archiving workspace users

.travis.yml, travis-after-success.sh, travis-install.sh
Closes #1017 will need further work though
=> Ftr 1017 speed up travis

muikku-core/src/main/java/fi/muikku/schooldata/CourseMetaController.java, muikku-core/src/main/java/fi/muikku/schooldata/GradingController.java, muikku-core/src/main/java/fi/muikku/schooldata/GradingSchoolDataController.java, muikku-core/src/main/java/fi/muikku/schooldata/RoleController.java, muikku-core/src/main/java/fi/muikku/schooldata/UserSchoolDataController.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceController.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceSchoolDataController.java, muikku-core/src/main/java/fi/muikku/session/local/LocalSessionControllerImpl.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
=> Changed LocalSessionControllerImpl to be CDI bean instead of EJB

muikku-atests-plugin/src/main/java/fi/muikku/atests/AcceptanceTestsRESTService.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java
=> Fix for deleting workspaces in tests

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceSystemRESTService.java, muikku-core/src/main/java/fi/muikku/schooldata/SchoolDataIdentifier.java, muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java, muikku-core/src/main/java/fi/muikku/users/UserSchoolDataIdentifierController.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java
=> Better sync for workspace users + manual maintenance tool

muikku-atests/src/test/java/fi/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/muikku/ui/base/course/users/CourseUsersTestsBase.java
=> Ftr 1019 student archive unarchive tests

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/UserPyramusClient.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/AbstractEntityCache.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/UserEntityCache.java
=> Bug 1047 login cache clean

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-file-field-component.js, muikku/src/main/webapp/resources/scripts/gui/muikku-field.js
File field component now triggers event on progress which resets the saveFailedTimer
=> Fixes #1011

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
** Changed evaluation button so that if users clicks it while browsing workspace, the evaluation view now loads that specific workspace.
=> fixes #991

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java
=> Fixed a bug causing WorkspaceUserDiscovered instead of WorkspaceUserUpdated

muikku/src/main/webapp/resources/scripts/api/api.js
=> Bug 1059 mapi abort

muikku-core-plugins/src/main/java/fi/muikku/plugins/search/SchoolDataIndexListeners.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/search/SchoolDataSearchReindexListener.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/search/UserIndexer.java
=> Bug 1055 user search doubles

muikku-core-plugins/src/main/java/fi/muikku/plugins/seeker/defaultproviders/WorkspaceSeekerResultProvider.java, muikku-core/src/main/java/fi/muikku/search/SearchProvider.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java
=> ** Fixes #1052

muikku/src/main/resources/META-INF/resources/dust/announcer/announcer_item.dust, muikku/src/main/webapp/resources/theme-muikku/sass/_announcer.scss
=> Listing announcements in announcer

muikku-core-plugins-persistence/src/main/java/fi/muikku/plugins/workspace/model/WorkspaceVisit.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceVisitController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/dao/WorkspaceVisitDAO.java, updates/1.0082/151210-unique-workspacevisit-workspaceanduser.xml
=> Bug 924 workspacevisit race condition

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
=> ** Fixes #1077 and  #1078

muikku-persistence/src/main/java/fi/muikku/model/plugins/PluginSetting.java, updates/1.0084/151210-unique-keyid-on-pluginsetting.xml
=> ** Fixes #1074

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java
=> ** Fixed bug #1096

muikku-core/src/main/java/fi/muikku/users/UserGroupEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserGroupEntityDAO.java
=> ** Fixes issue #1098

muikku-core-plugins/src/main/java/fi/muikku/plugins/guidancetool/GuidanceToolBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/guidancetool/GuidanceToolPermissions.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_page.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_user_filter.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_user_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_view_profile.dust, muikku-core/src/main/java/fi/muikku/users/UserEntityController.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java, muikku-rest/src/main/java/fi/muikku/rest/model/Student.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java, muikku/src/main/webapp/resources/scripts/gui/guider.js, muikku/src/main/webapp/resources/theme-muikku/sass/_animations.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_base.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_guider.scss
=> Ftr 1094 modernize guider

muikku-core-plugins-persistence/src/main/java/fi/muikku/plugins/workspace/model/WorkspaceToolSettings.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceToolSettingsController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/dao/WorkspaceToolSettingsDAO.java, muikku/src/main/webapp/facelets/generic/workspaces-main-dock.xhtml, updates/1.0084/151214_workspace_tool_settings.xml
=> ** Added support for specifying visible workspace tools

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> ** Added study programme name into evaluation dialogs

muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskM2Image.java
=> Cleaner task for fixing images from M2

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspacePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspacePluginMessages_fi.properties
=> ** Fixes #1112

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceArchiveAllStudentsBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/archive-all-students.xhtml, muikku-core/src/main/java/fi/muikku/security/MuikkuPermissions.java
=> Admin tool for archiving all students of a workspace

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-base-template.xhtml, muikku-core-plugins/src/main/resources/fi/muikku/plugins/frontpage/FrontPagePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/frontpage/FrontPagePluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspacePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspacePluginMessages_fi.properties, muikku-core/src/main/java/fi/muikku/controller/SystemSettingsController.java, muikku/src/main/java/fi/muikku/EnvironmentBackingBean.java, muikku/src/main/webapp/WEB-INF/templates/main-view.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/screen.scss
=> Ftr 1029 link to help

muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/AbstractHtmlMaterialCleanerTask.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskM2Image.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskMathMl.java
=> Proper modified handling of DNM cleaner tasks

muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataUserListener.java, muikku-core/src/main/java/fi/muikku/users/UserSchoolDataIdentifierController.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserSchoolDataIdentifierDAO.java
=> Unarchive support for UserSchoolDataIdentifiers

muikku/src/main/webapp/resources/theme-muikku/sass/_generic_context-view.scss, muikku/src/main/webapp/resources/theme-muikku/sass/announcement-view.scss
=> BUG 1145 Materials layout is broken visually

muikku-core-plugins/src/main/java/fi/muikku/plugins/guider/GuiderStudentWorkspaceActivity.java
=> ** Fixed issue #1148

muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/search/UserIndexer.java, muikku-core/src/main/java/fi/muikku/security/impl/EnvironmentPermissionResolver.java, muikku-core/src/main/java/fi/muikku/security/impl/WorkspacePermissionResolver.java, muikku-core/src/main/java/fi/muikku/users/UserGroupEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserGroupEntityDAO.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java
=> Bug 1154 user groups index

muikku/src/main/webapp/resources/theme-muikku/sass/_widgets.scss
=> * Fixed frontpage message widget's single message title's height limit

muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/dao/AnnouncementDAO.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/dao/AnnouncementUserGroupDAO.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/rest/AnnouncerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_edit_announcement.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js, muikku-rest/src/main/java/fi/muikku/rest/user/UserGroupRESTService.java
=> ** Fixes #1152

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
=> ** Fixed issue #1159

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
=> ** Evaluation request button now changes state on succesful request

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js
Fixes #1089 
Also creating announcements which have their enddate in
the past is blocked.
=> ** Date fields are now synchronized when creating or editing announcements

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-discussions.js
Fixes #1173 (Environment & workspace)
=> Discussion message author missing on pageload

muikku/src/main/webapp/resources/theme-muikku/sass/_fonts.scss
=> BUG 1174 character sets

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java
=>  - Added system session to workspace loading in coursepicker listworkspaces

muikku-bom/pom.xml, muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-rest/src/main/java/fi/muikku/rest/RestSessionFilter.java
Fixes #1144 
- Changed webapp-permission version from 1.0.1 to 1.0.2
- Added handling of RESTPermit.requireLoggedIn to RestSessionFilter
=>  - Added RESTPermit annotations to CommunicatorRESTService

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/ContentNode.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceFrontPageManagementBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceIndexBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialsBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialsManagementBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialsReadingBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/frontpage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-reading.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-editor-html.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-reading.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js, muikku-evaluation-plugin/src/main/java/fi/muikku/plugins/evaluation/EvaluationIndexBackingBean.java, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation_evaluate_single_assigment.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation_evaluate_workspace_single_assigment.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/index.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Ftr 1204 relative material urls

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/announcements/index.xhtml, muikku/src/main/webapp/WEB-INF/templates/generic-context-view.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/_announcer.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_generic_context-view.scss, muikku/src/main/webapp/resources/theme-muikku/sass/announcement-view.scss
=> * Removed dummy announcer image

muikku-calendar/src/main/resources/META-INF/resources/jsf/calendar/templates/calendar_base.xhtml, muikku-calendar/src/main/resources/META-INF/resources/scripts/gui/calendar.js, muikku-core-plugins/src/main/resources/META-INF/resources/dust/calendar/calendar_create_event.dust, muikku-google-calendar/src/main/java/fi/muikku/plugins/googlecalendar/Convert.java, muikku-google-calendar/src/main/java/fi/muikku/plugins/googlecalendar/GoogleCalendarClient.java, muikku-google-calendar/src/main/java/fi/muikku/plugins/googlecalendar/GoogleCalendarLoginListener.java, muikku-google-calendar/src/main/java/fi/muikku/plugins/googlecalendar/model/GoogleCalendar.java
Fixes #191
Fixes Datepicker bug in chrome
=> Calendar timezone

.travis.yml, muikku-atests-plugin-rest-model/src/main/java/fi/muikku/atests/Announcement.java, muikku-atests-plugin/src/main/java/fi/muikku/atests/AcceptanceTestsRESTService.java, muikku-atests/src/test/java/fi/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/muikku/ui/base/announcer/AnnouncerTestsBase.java, muikku-atests/src/test/java/fi/muikku/ui/chrome/announcer/AnnouncerTestsIT.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/dao/AnnouncementDAO.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/dao/AnnouncementUserGroupDAO.java, muikku-core/src/main/java/fi/muikku/users/UserGroupEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserGroupEntityDAO.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserGroupUserEntityDAO.java
=> Announcer tests closes #1168

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss
=> Bug 1208 example answers background

muikku-core-plugins-persistence/src/main/java/fi/muikku/plugins/websocket/WebSocketTicket.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/chat/ChatMessageHandler.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/websocket/WebSocket.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/websocket/WebSocketMessenger.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/websocket/WebSocketPingHandler.java, muikku/src/main/webapp/resources/scripts/gui/websocket.js, updates/1.0091/160119_wsticket.xml
=> Bug 1239 ws messenger stress

muikku/src/main/webapp/resources/theme-muikku/sass/screen.scss
Fixes #1256  everywhere in the environment
=> Supercript & subscript tag definitions to screen.css

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js, muikku-core/src/main/java/fi/muikku/search/SearchProvider.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java
=> ** Changed coursepicker to sort results by name and name extension

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js, muikku-core-plugins/src/main/resources/META-INF/resources/widgets/coursepicker-list-workspaces.xhtml, muikku-core-plugins/src/main/resources/fi/muikku/plugins/coursepicker/CoursePickerPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/coursepicker/CoursePickerPluginMessages_fi.properties, muikku-core/src/main/java/fi/muikku/search/SearchProvider.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java, muikku/src/main/webapp/resources/theme-muikku/sass/_coursepicker.scss
=> 1188 coursepickerpages

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss
=> * Added study programme indicator to evaluation view's student listing

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/CommunicatorAssessmentRequestController.java
=> ** Implemented feature #1199

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java
=> Workspace material NullPointerException fix

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js
=> Base URL for new documents

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
=> ** Fix for issue #1280

muikku-core-plugins-persistence/src/main/java/fi/muikku/plugins/websocket/WebSocketTicket.java, updates/1.0091/160119_wsticket.xml
=> ** Fixed issue #1283

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-rest/src/main/resources/fi/muikku/rest/workspace/WorkspaceRestMessages_en.properties, muikku-rest/src/main/resources/fi/muikku/rest/workspace/WorkspaceRestMessages_fi.properties
=> Ftr 360 new student message

muikku-core-plugins/src/main/java/fi/muikku/plugins/forgotpassword/ForgotPasswordRESTService.java
=> ** Set sender address when sending password reset emails, fixes #1287

muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/ForumResourcePermissionCollection.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/rest/ForumRESTService.java
=> ** Fixed issue #1295

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js
=> Shared HTML attachments

muikku-core-plugins/src/main/java/fi/muikku/plugins/material/rest/MaterialRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku-core/src/main/java/fi/muikku/security/MuikkuPermissions.java
=> Ftr 1211 linked material notification

muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/rest/AnnouncerRESTService.java
=> ** Fixes issue #1277

muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceEntityController.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceRedirect.java
=> ** Implemented feature #1304

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
=> ** Changed workspace material answers to be saved synchronously

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceHelpPageManagementBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/helppage-management.xhtml
=> Added base URL for help pages

.travis.yml
=> ** Removed IE 9 and Safari 8 from tests

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core/src/main/java/fi/muikku/schooldata/SchoolDataIdentifier.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java
=> Bug 1307 records

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_studyprogrammes.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core/src/main/java/fi/muikku/schooldata/SchoolDataIdentifier.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java, muikku/src/main/webapp/resources/theme-muikku/sass/_records.scss
=> Ftr 1321 nonmuicreds

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Material page anchor handling

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_studyprogrammes.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core/src/main/java/fi/muikku/schooldata/SchoolDataIdentifier.java, muikku-core/src/main/java/fi/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceUserEntityDAO.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java, muikku/src/main/webapp/resources/theme-muikku/sass/_records.scss
=> Ftr 1317 order workspaces alphabetically

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-students-active.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-students-inactive.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-teachers.dust, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-users.scss
=> * Added localization and check for workspace users listing when there

muikku-core-plugins/src/main/resources/fi/muikku/plugins/profile/ProfileJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/profile/ProfileJsPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/profile/ProfilePluginMessages_fi.properties
=> * Fixed typo in profile

muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_studyprogrammes.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_transfercredit.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_transfercredits.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core-plugins/src/main/resources/fi/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_fi.properties, muikku-core/src/main/java/fi/muikku/schooldata/GradingController.java, muikku-core/src/main/java/fi/muikku/schooldata/GradingSchoolDataBridge.java, muikku-core/src/main/java/fi/muikku/schooldata/GradingSchoolDataController.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/AbstractTransferCredit.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/TransferCredit.java, muikku-core/src/main/java/fi/muikku/security/MuikkuPermissions.java, muikku-rest/src/main/java/fi/muikku/rest/model/TransferCredit.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusIdentifierMapper.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusTransferCredit.java, muikku/src/main/webapp/resources/scripts/api/api.js, muikku/src/main/webapp/resources/theme-muikku/sass/_records.scss
=> Ftr 1329 records transfercredits

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-reading-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> ** Added a popup support into workspace material images

muikku-calendar/src/main/java/fi/muikku/plugins/calendar/CalendarController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/internalauth/InternalAuthenticationStrategy.java, muikku-core/src/main/java/fi/muikku/auth/AbstractAuthenticationStrategy.java, muikku-core/src/main/java/fi/muikku/auth/AuthSourceController.java, muikku-core/src/main/java/fi/muikku/auth/AuthenticationProvider.java, muikku-core/src/main/java/fi/muikku/auth/AuthenticationResult.java, muikku-core/src/main/java/fi/muikku/auth/OAuthAuthenticationStrategy.java, muikku-core/src/main/java/fi/muikku/auth/UserIdentificationController.java, muikku-core/src/main/java/fi/muikku/controller/PluginSettingsController.java, muikku-core/src/main/java/fi/muikku/controller/SystemSettingsController.java, muikku-facebook-oauth/src/main/java/fi/muikku/plugins/oauth/FacebookAuthenticationStrategy.java, muikku-google-calendar/src/main/java/fi/muikku/plugins/googlecalendar/GoogleCalendarClient.java, muikku-google-calendar/src/main/java/fi/muikku/plugins/googlecalendar/GoogleCalendarLoginListener.java, muikku-google-oauth/src/main/java/fi/muikku/plugins/oauth/GoogleAuthenticationStrategy.java, muikku-pyramus-oauth/src/main/java/fi/muikku/plugins/oauth/PyramusAuthenticationStrategy.java, muikku/src/main/java/fi/muikku/auth/LoginBackingBean.java
=> ** Removed @Stateless annotations from various beans because they made

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceHelpPageBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml
=> Base URL for workspace help page

muikku/src/main/webapp/resources/theme-muikku/sass/_connectionlost.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_custom-ckeditor-modal.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_dialog.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_fonts.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_jquery.datepicker.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_mainfunctions.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_widgets.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces.scss, muikku/src/main/webapp/resources/theme-muikku/sass/custom-ckeditor-contentcss.scss, muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss, muikku/src/main/webapp/resources/theme-muikku/sass/muikku-file-field-component.scss, muikku/src/main/webapp/resources/theme-muikku/sass/screen.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-discussions.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-journal.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-management.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-reading.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-profile.scss
=> Ftr 1376 font change

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-discussions.js
=> ** Fix for issue #1384

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/HtmlMaterialCleaner.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/HtmlMaterialCleanerTask.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskAudioControls.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskBase64Image.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskIxNamespaces.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskM2Image.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskMathMl.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskRelativeWorkspaceMaterialResources.java, muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/util/TaskSrcQueryParams.java
=> Base64 image support and cleaner task

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceController.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceSchoolDataBridge.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceSchoolDataController.java, muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
=> Improved Pyramus sync for students and their workspace signups

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/CourseParticipationTypeEvaluationMapper.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusIdentifierMapper.java
=> ** Added support changing course participation types in Pyramus when

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerWorkspace.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js, muikku-rest/src/main/java/fi/muikku/rest/model/UserBasicInfo.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java, muikku-school-data-pyramus/src/main/resources/pyramus-rest-cache-config.json
=> Bug 1406 slow picker

muikku-core/src/main/java/fi/muikku/session/local/LocalSessionControllerImpl.java
=> ** Fixed issue #1399

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js
=> ** Changed course picker search input to be disabled when search is

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Image hyperlink fix

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/User.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/UserGroup.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/Workspace.java, muikku-core/src/main/java/fi/muikku/search/IndexableEntityVault.java, muikku-core/src/main/java/fi/muikku/search/SearchConfiguratorCDIExtension.java, muikku-core/src/main/java/fi/muikku/search/annotations/Indexable.java, muikku-core/src/main/java/fi/muikku/search/annotations/IndexableFieldMultiField.java, muikku-core/src/main/java/fi/muikku/search/annotations/IndexableFieldOption.java, muikku-core/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchIndexUpdater.java
=> Bug 1317 orders

muikku-core-plugins/src/main/resources/fi/muikku/plugins/coursepicker/CoursePickerJsPluginMessages_en.properties, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java
=> ** Fixed issue #1411

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core/src/main/java/fi/muikku/mail/Mailer.java
=> ** Teacher(s) of the workspace are now notified with email

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-discussions.js
The test for empty message was missing from reply
Fixes #1223
=> Fixes #1223

muikku-core-plugins/src/main/java/fi/muikku/plugins/material/operations/HtmlMaterialCloneOperation.java
=> Workspace HTML material clone bug fix

muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/rest/ForumRESTService.java, muikku/src/main/webapp/resources/scripts/api/api.js
=> Ftr 1424 mapi errors

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceBackingBean.java
=> Set Workspace Members button visible only to those with manage members permission

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-reading.js
=> ** Removed calls to non-existing method refresh of muikkuConnectField

muikku-core-plugins/src/main/java/fi/muikku/plugins/language/LanguageWidgetBackingBean.java, muikku-core/src/main/java/fi/muikku/auth/AbstractAuthenticationStrategy.java, muikku-core/src/main/java/fi/muikku/users/UserEntityController.java, muikku-persistence/src/main/java/fi/muikku/dao/users/UserEntityDAO.java, muikku-persistence/src/main/java/fi/muikku/model/users/UserEntity.java, updates/1.0099/160209_locale.xml
=> ** Added support for persisting user's locale

muikku-atests/src/test/java/fi/muikku/ui/base/course/users/CourseUsersTestsBase.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-students-active.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-users-students-inactive.dust
=> ** Added study programme info into workspace users list

muikku-core-plugins/src/main/java/fi/muikku/plugins/transcriptofrecords/TranscriptofRecordsBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item_assignment.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku/src/main/webapp/resources/theme-muikku/sass/_records.scss
=> Ftr 1422 tor colors

muikku-core-plugins/src/main/java/fi/muikku/plugins/schooldatalocal/LocalUserSchoolDataBridge.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/schooldatalocal/entities/LocalUserImpl.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/AbstractUser.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/User.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusUser.java
=> ** Fixes #1450

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/model/WorkspaceFolder.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js
=> Updating of material paths when material titles change in material management. Material.

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java
=> Added null checks to PyramusUpdater

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core/src/main/java/fi/muikku/search/SearchProvider.java, muikku-core/src/main/java/fi/muikku/security/MuikkuPermissions.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java
=> List credits of old study programmes

muikku-atests/src/test/java/fi/muikku/rest/test/PyramusMocksRest.java, muikku-atests/src/test/java/fi/muikku/rest/users/test/UserRESTServiceTestsIT.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java
=> Proper synchronization of workspace students who have ended their studies

muikku-atests/src/test/java/fi/muikku/AbstractIntegrationTest.java, muikku-atests/src/test/java/fi/muikku/TestUtilities.java, muikku-atests/src/test/java/fi/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/muikku/mock/model/MockStudent.java, muikku-atests/src/test/java/fi/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/muikku/ui/PyramusMocks.java, muikku-atests/src/test/java/fi/muikku/ui/base/GuiderTestsBase.java, muikku-atests/src/test/java/fi/muikku/ui/base/announcer/AnnouncerTestsBase.java, muikku-atests/src/test/java/fi/muikku/ui/base/course/users/CourseUsersTestsBase.java, muikku-atests/src/test/java/fi/muikku/ui/base/evaluation/EvaluationTestsBase.java, muikku-calendar/src/main/java/fi/muikku/plugins/calendar/JPACacheFlushListener.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/JPACacheFlushListener.java, muikku-core/src/main/java/fi/muikku/cache/CacheFlushEvent.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/JPACacheFlushListener.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/CacheFlushListener.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/cache/EntityCacheEvictor.java, muikku/src/main/java/fi/muikku/system/SystemCacheFlushBackingBean.java, muikku/src/main/webapp/jsf/system/cache-flush.xhtml, test.sh
=> Bug 1462 userlist tests failing

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/socialnavigation.js
=> Fix for messages not delivered when multiple recipients are present

muikku-core-plugins/src/main/resources/META-INF/resources/widgets/home-info.xhtml
=> ** Updated front page text

muikku-core-plugins/src/main/java/fi/muikku/plugins/websocket/WebSocketRESTService.java, muikku/src/main/webapp/resources/scripts/api/api.js, muikku/src/main/webapp/resources/scripts/gui/websocket.js
=> Bug 1464 ms edge answers

muikku-core/src/main/java/fi/muikku/schooldata/entity/User.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/Workspace.java, muikku-core/src/main/java/fi/muikku/search/IndexEntityProcessor.java, muikku-core/src/main/java/fi/muikku/search/annotations/IndexField.java
=> ** Changed search index to skip DateTime fields when indexing

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_sent_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Faster Communicator sent (and in)box

muikku-core-plugins/src/main/resources/META-INF/resources/dust/frontpage/widget_visit.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-visits.js, muikku/src/main/webapp/resources/theme-muikku/sass/_widgets.scss
=> Bug 1485 name extensions

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_messagerecipient.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_messagerecipientgroup.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_messagerecipientworkspace.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Ftr 1477 communicator workspace name extension missing

muikku-core-plugins/src/main/java/fi/muikku/plugins/coursepicker/CoursePickerRESTService.java
=> Unarchive workspace student when enlisting to a workspace

muikku/src/main/webapp/resources/theme-muikku/sass/_custom-ckeditor-styles.scss
=> * Removed forced display:none from br element which is inside citation

muikku-core/src/main/java/fi/muikku/mail/MailAttachment.java, muikku-jndi-mail-bridge-plugin/src/main/java/fi/muikku/plugins/mail/jndi/JndiMailBridge.java, muikku-jndi-mail-bridge-plugin/src/main/java/fi/muikku/plugins/mail/jndi/JndiMailBridgePluginDescriptor.java, muikku-jndi-mail-bridge-plugin/src/main/java/fi/muikku/plugins/mail/jndi/JndiMailEvent.java, muikku-jndi-mail-bridge-plugin/src/main/java/fi/muikku/plugins/mail/jndi/JndiMailService.java
=> Bug 1489 slow mail

muikku-core-plugins/src/main/java/fi/muikku/plugins/websocket/WebSocketMessenger.java
=> ** Fixes issue #1501

muikku-core/src/main/java/fi/muikku/schooldata/events/DefaultSchoolDataUserGroupListener.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusUpdater.java
=> ** Fixed issue #1504

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/SystemAccessTokenProvider.java, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/rest/SystemPyramusClient.java
=> Singleton provider for system access tokens

muikku-core-plugins/src/main/java/fi/muikku/plugins/search/SchoolDataIndexListeners.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/search/UserIndexer.java
=> ** Fixes issue #1513

muikku-core-plugins/src/main/java/fi/muikku/plugins/announcer/AnnouncementsViewBackingBean.java
=> ** Show only announcements targeted to logged user entity

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-file-field-component.js, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
=> ** Fixed bug #194

muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/ForumAreaOwnerContextResolverImpl.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/ForumResourcePermissionCollection.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/rest/ForumRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-discussions.js
=> Correct permissions for deleting workspace forum areas

updates/1.0100/160224_utf8mb4.xml
=> ** Added update script that fixes problems with utf8mb4

muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
- fix for #1544 (requires Pyramus build)
=> Bug fix for listing workspace assessment requests

muikku-core-plugins/src/main/java/fi/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
=> Removed unnecessary assessment request error logging

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js
=> ** Changed muikku-connect-field-component to trigger change only when

muikku-core-plugins/src/main/java/fi/muikku/plugins/search/UserIndexer.java, muikku-core/src/main/java/fi/muikku/schooldata/SchoolDataIdentifier.java, muikku-core/src/main/java/fi/muikku/schooldata/WorkspaceEntityController.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/User.java, muikku-core/src/main/java/fi/muikku/schooldata/entity/Workspace.java, muikku-elastic-search/pom.xml, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchIndexUpdater.java, muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java, muikku-persistence/src/main/java/fi/muikku/dao/workspace/WorkspaceEntityDAO.java, muikku-rest/src/main/java/fi/muikku/rest/model/Student.java, muikku-rest/src/main/java/fi/muikku/rest/user/UserRESTService.java
=> Bug 1536 student activity

muikku/src/main/webapp/index.xhtml
=> Phrasing changes to front page instructions

muikku/src/main/webapp/index.xhtml
=> Correct description text in front page

muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-management.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-reading.scss
=> * Fixed too wide images ratio issues with wrkspace materials

muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
=> ** Bumped CKEditor into version 4.5.7 in evaluation view.

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> ** Changed evalution view to clear out students before adding new ones

muikku/src/main/webapp/resources/theme-muikku/sass/_communicator.scss
=> * Added margins for paragraphs inside communicator messages

muikku-core-plugins/src/main/java/fi/muikku/plugins/communicator/rest/CommunicatorRESTService.java
=> Fix to show latest communicator threads first

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceJournalBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml
=> Journal students sorted by surname

muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/ForumController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/forum/rest/SystemForumRESTService.java, muikku-core/src/main/java/fi/muikku/controller/ResourceRightsController.java, muikku-persistence/src/main/java/fi/muikku/dao/security/ResourceRolePermissionDAO.java
- system utility that fixes #1572
=> System utility for resetting individual forum area rights to their current defaults

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js
=> Fix for crash when editing journal entries

muikku-core-plugins-persistence/src/main/java/fi/muikku/plugins/workspace/model/WorkspaceJournalEntry.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceJournalBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceJournalController.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/dao/WorkspaceJournalEntryDAO.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js, updates/1.0103/160310_journal.xml
=> Journal create entry bug fix

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml
=> * Fixed MS edge issue when materials TOC overlays content

muikku-calendar/src/main/resources/META-INF/persistence.xml, muikku-core-plugins-persistence/src/main/resources/META-INF/persistence.xml, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java, muikku-core/src/main/java/fi/muikku/controller/PluginSettingsController.java, muikku-evaluation-plugin-persistence/src/main/resources/META-INF/persistence.xml, muikku-persistence/src/main/resources/META-INF/persistence.xml, muikku-school-data-pyramus-persistence/src/main/resources/META-INF/persistence.xml, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, travis-after-success.sh
- resolves #1679
- fixed a forever loop in WorkspaceMaterialController
- logging of plugin setting gets
- application scoped PyramusSchoolDataEntityFactory
- disable Deus Nex Machina
=> Muikku performance troubleshooting

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/rest/WorkspaceRESTService.java
=> ** Quote&escape filename in Content-Disposition field

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js
=> * Adjusted topOffset in materials scrolling

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_jquery.datepicker.scss
=> * Fixed workspace copy wizard's datepicker styles

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js
=> Unique folder URL names and temporary fix for create + edit concurrency crash

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml, muikku-school-data-pyramus/src/main/java/fi/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
=> If course subject does not specify education type, use course education type instead

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceHelpPageBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceIndexBackingBean.java, muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialsBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml
=> Restored latest workspaces functionality

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-reading.scss
=> Ftr 1611 pdf article

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_custom-ckeditor-styles.scss
=> * Fixed missing file icon's path

muikku-elastic-search/src/main/java/fi/muikku/plugins/search/ElasticSearchProvider.java
=> ** Fixes #1536

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/cache/EntityCacheEvictor.java
=> ** Fixed issue #1732

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/coursepicker/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku/src/main/webapp/WEB-INF/templates/default.xhtml, muikku/src/main/webapp/index.xhtml
=> * Updated perfect scrollbar to 0.6.10 from 0.6.5 to fix usability bugs

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java
=> ** Fixed #1752

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
=> ** Fixes #1744

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml
=> ** Specify <option>s properly as JSF passthrough elements

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/fieldmeta/MemoFieldMeta.java, muikku-deus-nex-machina/src/main/java/fi/otavanopisto/muikku/plugins/dnm/translator/FieldTranslator.java
=> ** Correct metadata for richedit field

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceStudent.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/AbstractWorkspaceUser.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/WorkspaceUser.java, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusWorkspaceUser.java, muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss
=> Ftr 1704 joined date evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_create_message.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_edit_message.dust, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_forms.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/discussion.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Ftr 1773 generic ui improvements

muikku-core-plugins/src/main/resources/META-INF/resources/dust/frontpage/widget_workspace.dust
=> Name extensions for widget

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_notif-queue.scss
=> Warning message for students checking out courses they cannot sign up to

muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
=> ** Fixed NPE on ElasticSearchProvider

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_messagerecipientgroup.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Fixe a bug by adding usergroups, teacher & student workspaces

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-reading-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-editor-html.js
=> Ftr 1742 textarea autogrow

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceEntityController.java
=> Set access of new workspaces to LOGGED_IN

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/AbstractWorkspaceBackingBean.java
=> ** Fixed issue #1805

muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss
=> Bug 1808 textfield hint evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-reading-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Ftr 1749 textfield scaling

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
=> Student's study programme in signup message to teachers

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/logindetails/LoginDetailController.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_profile_workspaces.dust
=> ** Fixed issue #1819

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-reading-view.xhtml
=> * Added MAthJax lib to material view's where it was missing

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku-mongo-log/src/main/java/fi/otavanopisto/muikku/plugins/mongolog/MongoLogProvider.java, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-management.scss
=> Ftr 1816 guider flagging

muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepickercourse.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepickermycourse.dust, muikku/src/main/webapp/resources/theme-muikku/sass/flex/coursepicker.scss
=> Ftr 1821 coursepicker fee tuning

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_item_details.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guidancetool/GuidanceToolJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guidancetool/GuidanceToolJsPluginMessages_fi.properties, muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserGroupRESTService.java, muikku/src/main/webapp/resources/theme-muikku/sass/_guider.scss
=> Add student groups to guider

muikku/src/main/webapp/index.xhtml
=> ** Fixed frontpage info text, closes #1798

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-index-material-producers.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-index.scss
=> Ftr 1686 workspace authors

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml
=> ** Bumped jquery.license-selector version into 0.0.4 (fixes issues

muikku-evaluation-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/rest/model/WorkspaceMaterialEvaluation.java, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
- added pass/fail flag to WorkspaceMaterialEvaluation
- updating of assignment evaluation to passed/failed
- fixes #1784
=> Proper updating of assignment passed/failed status based on given grade

muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityController.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/UserGroupUserEntityDAO.java
=> Archived flag handling for listing user group users

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-management.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
=> Evaluation launched from workspace opens to that workspace by default

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/language/LanguageWidgetBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/discussion/index.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-workspace.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Ftr 97 language change workspace

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
=> Added workspace name extension to signup notifications

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-image-details.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-management.scss, muikku/src/main/webapp/resources/theme-muikku/sass/workspaces-materials-reading.scss
Fixes #1859 Fixes #1860 Fixes #1861 Fixes #1862
=> * Fixes multiple layout issues with image license, source and author

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-image-details.js
=> ** Fixed issue #1863

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/theme-muikku/sass/custom-ckeditor-contentcss.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss.scss
=> Bug 1869 custom content css

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forgotpassword/ResetPasswordBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/user/UserPendingPasswordChangeDAO.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/forgotpassword/reset.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/forgotpassword-reset.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordJsPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forgotpassword/ForgotPasswordPluginMessages_fi.properties, muikku-core/src/main/java/fi/otavanopisto/muikku/jsf/NavigationController.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java, muikku/src/main/webapp/resources/theme-muikku/sass/flex/forgot-password.scss, muikku/src/main/webapp/resources/theme-muikku/sass/screen.scss
=> Ftr 1400 forgot username

muikku/src/main/webapp/resources/theme-muikku/sass/_forms.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_guider.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_forms.scss
=> * Added search icon for coursepicker and guider (2 different _forms.scss

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-audio-defaults/plugin.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-editor-html.js
=> Added CKEditor plugin for changing audio plugin defaults

muikku/src/main/webapp/resources/theme-muikku/sass/_announcer.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_jquery.datepicker.scss
=> Proper styling for date picker month navigation buttons

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceRedirectsRewriteConfiguration.java
=> Fixes issue #200

travis-after-success.sh
=> ** Set upstream when pushing changes to devel

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Bug fix for batch deletion of sent communicator messages

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js
=> Course picker search field that won't lose focus when typing

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml
=> * Added Mathjax lib to help and index pages in workspace

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-image-details/plugin.js
=> Correct order of source, author, and license fields

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core/src/main/java/fi/otavanopisto/muikku/controller/PluginSettingsController.java, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Ftr 1616 select field layout

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_fi.properties
=> Notifications on failed assignments

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml
=> Workspace diary "show all" choice

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml
=> ** Bumped jquery.license-selector version

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml
=> * Added image license, source and author scripts to workspace index and

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/coursepicker/index.xhtml
=> * Fixed course pickers filters responsive views for md and sm

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/discussions/CourseDiscussionTestsBase.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/scripts/debug.js, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/evaluation.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss, test.sh
=> Fixed #398

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/announcer/AnnouncerTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/journal/CourseJournalPageTestsBase.java
=> Bug 1946 journal test

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/announcer/AnnouncerTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/journal/CourseJournalPageTestsBase.java
=> Bug 1943 announcertest

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
=> ** Fixing filefield tests

muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
=> Search workspaces with multiple words

muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/forum/ForumMessagePermissionsTestsIT.java, muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/forum/model/ForumThreadReply.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_reply.dust, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumJsPluginMessages_fi.properties, muikku-forum-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumThreadReplyRESTModel.java, muikku/src/main/webapp/resources/theme-muikku/sass/flex/discussion.scss
=> Ftr 1921 show number of replies to reply

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-image-details.js
=> Proper image details punctuation

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> ** Evaluation date is now automatically updated to current date if grade is is changed.

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> ** Order students by name when evaluating

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Fixed issue #1985

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> ** The assignment can always be evaluated, fix #1993

.travis.yml, muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractIntegrationTest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/user/UserTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/user/UserTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/user/UserTestsIT.java
=> Ftr 1853 password reset username

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/picker/CoursePickerTestsBase.java
=> ** CoursePicker paging test

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
=> * Fixed MathJax loading

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
=> Wait for unsaved fields when submitting an answer

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Bug 1970 evaluation grid view's scrolling

muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java
=> Proper handling of workspace scoped permissions for user groups

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Fixed issue #1979

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-image-target/plugin.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-editor-html.js
=> Fixes #1967

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/index.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss
=> Ftr 1923 evaluation flag filter

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/guider/templates/guider_base.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java, muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java, muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
=> Bug 1660 data transfer prohibition

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/coursepicker/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/discussion/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/widgets/coursepicker-change-view.xhtml, muikku/src/main/webapp/WEB-INF/templates/default.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-env.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml, muikku/src/main/webapp/facelets/generic/workspaces-edit-dock.xhtml
=> Additional study programme leader checks

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/announcer/AnnouncerTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java
=> ** Fixes tests

muikku-bom/pom.xml, muikku-core-plugins/pom.xml
=> Bumped cyberneko to version 1.9.22 (fixes issue #2035)

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-reading-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-word-definition.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Bug 1935 word def zindex

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Fixes #2065

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss
=> * BUG - 2038 Dates overlapping with student names

muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> * Fixed last right aligned items overflow issue

muikku/src/main/webapp/facelets/generic/dock-top-left.xhtml
=> * BUG - 2061 Search icon in non-flexed views

muikku/src/main/webapp/resources/theme-muikku/sass/_custom-ckeditor-styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_custom-ckeditor-styles.scss
=> * Fixed font size issues in workspace materials

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js
=> MathJax for students (in rich edit memos)

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java
=> Quick fix to prevent duplicating workspace staff member roles

muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> * Added font-size properties to tables as defaults ion material's views

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/styles/workspace-material-styles.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/_custom-ckeditor-styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_custom-ckeditor-styles.scss
=> FTR - 2050 Grammar Box

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-helppage.js
=> * Added seperate script for workspace helps instead of using frontpage

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> * Fixed workspace evaluation dialog not opening

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js
=> Sorter field correct answers

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_draft.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss
=> Bug 2109 communicator styles

muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss
=> * Added styles for organizers and sorter fields in evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js
=> Read-only handling for sorter fields

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace_announcements.xhtml
=> Fixed issue #2124

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
closes #2095, closes #2096, closes #2094
=> ** AsciiMath support testing

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/materials-page-license-producers-orveride.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> * Added initial implementation to material's license and producer

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-index-material-license.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-index-material-producers.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-index.scss
=> * Added workspace license to workspace frontpage

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-signup-dialog.js
=> Proper title for signing up to a workspace

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementsViewBackingBean.java
=> Environment announcements only to logged in users

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/announcer/AnnouncerTestsBase.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_widget_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-announcements.js, muikku/src/main/webapp/index.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/frontpage.scss
=> Frontpage announcements

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
- resolves #2141 (cannot reproduce; now with more server logging)
- changed deprecated hasCoursePermission calls to hasWorkspacePermission
=> More server log to pinpoint workspace / workspace user mismatches

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/guider/index.xhtml
=> Fixes 2154

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/coops/rest/CoOpsRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/BinaryMaterialRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/rest/HtmlMaterialRESTService.java, muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java
=> Material management permissions

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_share_flag.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss
=> Fix the flag share autocomplete

muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_reply.dust
=> Fixed #2152

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceBackingBean.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java, muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java, muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml, muikku/src/main/webapp/facelets/generic/workspaces-assessment-dock.xhtml
=> Fix for workspace assessment state resolved via Pyramus multiple times per page load

.travis.yml, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/GuiderTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/guider/GuiderTestsIT.java
=> Bug 2162 guider tests not running

muikku/src/main/webapp/facelets/generic/header-right.xhtml
=> Removed reference to widget loggeduser, which was removed earlier

muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust
=> Show workspace name extension in ToR as needed

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-copy-wizard.js, muikku/src/main/webapp/resources/scripts/gui/locales.js
=> Workspace name rendering fix to copy workspace wizard

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/scripts/api/api.js
=> Better concurrency in evaluation view

muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_widget_item.dust, muikku/src/main/webapp/resources/theme-muikku/sass/flex/frontpage.scss
=> Announcer front page widget paddings

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
=> Ftr 2132 re enable ascii math tests

muikku/src/main/webapp/resources/theme-muikku/sass/_custom-ckeditor-styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_custom-ckeditor-styles.scss
=> * Removed max-width and margin auto restrictions from custom div styles

muikku/src/main/webapp/resources/theme-muikku/sass/custom-ckeditor-contentcss.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspaces-materials-management.scss
=> * Fixed issue where editor's font size was too large

muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspaces-materials-management.scss
=> * Added missing ckeditor modal scss file

.hound.yml, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/fieldmeta/TextFieldMeta.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-textfield/lang/en.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-textfield/lang/fi.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-textfield/plugin.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-deus-nex-machina/src/main/java/fi/otavanopisto/muikku/plugins/dnm/FieldElementsHandler.java, muikku-deus-nex-machina/src/main/java/fi/otavanopisto/muikku/plugins/dnm/parser/content/DeusNexContentParser.java, muikku-deus-nex-machina/src/main/java/fi/otavanopisto/muikku/plugins/dnm/parser/content/DeusNexFieldElementHandler.java, muikku-deus-nex-machina/src/main/java/fi/otavanopisto/muikku/plugins/dnm/translator/FieldTranslator.java
=> Optional autogrow for text fields

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss
=> * Fixed issue with perfect scrollbar crash, lib is not even needed

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/guider/GuiderTestsIT.java
=> ** Moving guider test to correct local package

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/announcer/AnnouncerTestsIT.java
=> ** Adding missing sauce package for announcer

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-textfield/lang/fi.js
=> Fixed a typo in text field properties dialog

.travis.yml, muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/announcer/CourseAnnouncerTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/course/announcer/CourseAnnouncerTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/course/announcer/CourseAnnouncerTestsIT.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java
=> Ftr 2117 workspace announcer tests

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js
=> Fixes issue #2227

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
=> ** hasCoursePermission into hasWorkspacePermission in

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-copy-wizard.js
=> Correct REST endpoint for copying workspace discussion areas

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-image-details.js
=> Fix for images showing too small; now uses correct value for figure max-width 

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementsViewBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
=> If user has permissions all evironment announcements are listed

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml
=> ** Fixes #2241

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java
=> Ftr 2163 material license override test

muikku-developer-tools/src/main/java/fi/otavanopisto/muikku/developertools/rewrite/WebLibFolderFinder.java
=> Windows path handling fix for developer-tools

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-image-details.js
=> Bug 2264 incorrect image size

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-mathjax/plugin.js
=> MathJax undefined fix

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> ftr 2263 bulletin style type

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml
=> Bug 2260 Workspace frontpage image's issues

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/profile.js
=> Profile view undefined fix

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-word-definition/dialogs/definition.js
=> Word definition null fix

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-reading.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_environment_print.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace_print.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials-reading.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials.scss
=> Ftr 2285 print styles for materials

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/login.js, muikku-core-plugins/src/main/resources/META-INF/resources/widgets/login.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-env.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/_base.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_buttons.scss, muikku/src/main/webapp/resources/theme-muikku/sass/_widgets.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_buttons.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Ftr 2257 better forgot password

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js
=> Blocks the search when the announcer is already chosen.

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketMessenger.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/SaveFieldAnswerWebSocketMessageHandler.java
- additional logging for missing user entity id
- ignore closed channels in websocket messaging
=> Minor changes to assist in resolving websocket problems

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/WorkspaceFileFieldIOHandler.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-file-field-component.js
- fixes #2255 (?)
- file field to only save once when replacing a file
- increased save fail timeout from 1 to 5 seconds
=> Fix for file field connection lost (?)

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js
=> Horizontal sorter fix

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-fields/plugin.js
=> Fix for multiple pasted fields getting same name

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js
=> Fix for calling sortable methods when the widget has not been initialized

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss, pom.xml
=> Bug 2325 student font size evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js
=> Connection field duplicate counterpart support

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Proper handling of mailto links in materials

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js
=> Changed sorter correct answer checking to cope with identical words

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
=> Fix for UserSchoolDataBridge not handling null staff members properly

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/login.js
=> Fix for multiplying forgot password dialogs + better address handling

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/announcer/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/coursepicker/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/discussion/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/guider/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/records/index.xhtml, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/announcer/AnnouncerPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/announcer/AnnouncerPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderPluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsPlugin_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsPlugin_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Ftr 2349 page titles

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_mobile.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Bug 2303 new message footer

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspacePermissionsManagementBackingBean.java
=> Plugin setting for filtering groups shown in workspace permissions view

muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation_evaluate_single_assigment.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation_evaluate_workspace_single_assigment.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss
=> Ftr 2326 evaluation submit time

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/WorkspaceForumRESTService.java
=> Enabled forum message link target

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
=> Fix for 403 requesting courses (Papertrail)

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-announcements.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-courselist.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-visits.js
=> Bug 2361 mobile page scrolling broken

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Fix for incorrectly rendered assignment dates in evaluation view

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
=> Save assessment first, send notification after

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/UserIndexer.java
=> Remove archived Pyramus users from Muikku search index

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceMaterialFileFieldAnswerFile.java, updates/1.0144/160909_fileid.xml
=> Indexed fileId of WorkspaceMaterialFileFieldAnswerFile

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
=> Removed unnecessary system session in WorkspaceRESTService

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketMessenger.java, muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityController.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/UserGroupUserEntityDAO.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusSchoolDataUserListener.java
=> Fixed students inadvertently being archived from study programmes

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js
=> ** Un-typeset and re-typeset connect field values to fix #2289

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Ftr 2362 tables scrolling

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/SaveFieldAnswerWebSocketMessageHandler.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/WorkspaceFileFieldIOHandler.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/WorkspaceCompositeReply.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-file-field-component.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPagePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPagePluginMessages_fi.properties, muikku/src/main/webapp/WEB-INF/templates/default.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_file-field.scss
=> File field to support multiple files and to stop crashing all the time

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerWorkspace.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepickercourse.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/coursepicker/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-management.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_fi.properties, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-management.scss
=> Workspace copy bug fix + moved functionality from course picker to workspace settings

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-reading.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials-management.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials-reading.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials.scss
=> Ftr 2287 materials toc lock icon

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/WorkspaceAnnouncementsViewBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/WorkspaceAnnouncerBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceDiscussionsBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceFrontPageManagementBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceHelpPageBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceHelpPageManagementBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialUploadBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialsBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialsManagementBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialsReadingBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspacePermissionsManagementBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspacePermissionsRoleManagementBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/users.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-materials-fullscreen-view.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-discussions.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-journal.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-users.scss
=> Ftr 2406 workspace name

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceEntityController.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceEntityDAO.java
=> Removes most access to archived workspaces

.eslintrc.json
Potential fix for hound barking at mApi and renderDustTemplate.
=> Add mApi and renderDustTemplate to eslint globals

muikku/pom.xml
=> Ftr 2428 minify css

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-reading.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsJsPlugin_fi.properties, muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java, muikku/src/main/webapp/facelets/generic/dock-top-left.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/records.scss
=> Workspace journal entries to Table of Records

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketMessenger.java
=> Websocket concurrency and leak fix

muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
=> Fix for all courses listed for non-logged in users

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
=>  - Added duplicate recipient cleaning to message sending

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> replying to own message

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/lazyframe.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
=> Load material iframes only when they enter viewport

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceBinaryMaterialServlet.java
=> Byte range support for workspace binaries

.eslintrc.json
Added async, getLocaleText and MUIKKU_LOGGED_USER_ID into hound globals
=> Added more globals for hound

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/communicator/model/CommunicatorMessage.java, muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/communicator/model/CommunicatorMessageId.java, muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/communicator/model/CommunicatorMessageRecipient.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/dao/CommunicatorMessageDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/dao/CommunicatorMessageRecipientDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorTrashRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorPluginMessages_fi.properties, updates/1.0146/160919-communicator-trash.xml
=> Ftr 2294 communicator trash

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java
=> More informative PyramusUserSchoolDataBridge errors

.eslintrc.json
Added MUIKKU_LOGGEDIN to hound globals
=> Added one more global for hound

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
=> Journal entries back to evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item_label.dust, muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> * Communicator UX improvements (color and visual changes)

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/SystemAccessTokenProvider.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/UserPyramusClient.java
=> Synchronized REST access token handling

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/lazyframe.js
=> Limit open iframes to four (fixes audio bug caused by too many AudioContexts)

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-file-field-component.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js, muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/_forms.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_audio-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_ckeditor_theme.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_connect-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_correct_answers.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_file-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_organizer-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_sorter-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation.scss
=> Bug 2460 start stop icons missing

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/discussion/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/discussions.xhtml
=> ** Fixed discussion's icons background issues

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
=> Fix for workspace teachers not being able to manage workspace announcements

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/SaveFieldAnswerWebSocketMessage.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/SaveFieldAnswerWebSocketMessageHandler.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
=> When saving answers, resolve user from WS message rather than event

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Fix for assignment without fields not holding its state

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_tools_thread.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Ftr 2570 toolbar does not update after reply

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js
=>  - Added a little bit better handling of filter changes to coursepicker

muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/CommunicatorUserLabelRESTModel.java, muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/journal/CourseJournalPageTestsBase.java
=> ** Label and trash testing for communicator

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js
=> ** Handle nested elements correctly in connect field

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/materials-management-page-binary.dust
=> Show image binaries in materials management

muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
=> Proper course picker filter for members only workspaces

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Iframe relative source path fix

muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/forum/ForumPermissionsTestsIT.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumResourcePermissionCollection.java, updates/1.0151/161012_spleader_deletearea.xml
=> Added right to delete forumarea to manager and studyprogramme leader

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/WorkspaceIndexer.java, muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
=> Added subject to workspace index

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceDiscussionsBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/discussions.xhtml
=> Added permission checks for workspace forum area admin tools

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss
=> guider colors to vars

muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss
=> Ftr 2553 communicator visual enhancements

muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
=> Ftr 2508 google analytics

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
=> Removed sender from recipients when (s)he is part of a recipient group

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTModels.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Bug 2565 broken pipe

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NotificationController.java
=> ** Timed notifications dry run mode

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/announcer.scss
=> Announcer colors to vars

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku-elastic-search/.gitignore
=> Adds onclick event on document and filter click to hide menus

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_tools_thread.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_fi.properties
=> Mark messages read ui, script & locales

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderPermissions.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_view_profile.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss
=> Preview attachment files in guider

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java, muikku-atests/src/test/resources/muikku-data/test/test-data.sql
=> ** Guider/ToR test

muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/AbstractWorkspace.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/Workspace.java, muikku-core/src/main/java/fi/otavanopisto/muikku/search/IndexEntityProcessor.java, muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusWorkspace.java
Fixes #2355 
Might be dependent on https://github.com/otavanopisto/pyramus/pull/414
=> Added support for multiple curriculums on workspaces

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NotificationController.java
=> Ftr 2540 statistics on timed notifications

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Ftr 1783 communicator replying

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_connect-field.scss
=> Connect field breaks

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_organizer-field.scss
=> Bug-2583 organizer line-breaks

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/evaluation/EvaluationTestsBase.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
=> Fix for Muikku compilation issues

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-management.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku/src/main/webapp/resources/scripts/gui/dustloader.js
=> Moment.js refactoring

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-word-definition.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_sorter-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss_management.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss_reading.scss
=> Word definition mobile support

muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/forum/ForumMessagePermissionsTestsIT.java, muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/forum/model/ForumThreadReply.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/dao/ForumThreadReplyDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/WorkspaceForumRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_reply.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/environment-discussion.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-discussions.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/forum/ForumJsPluginMessages_fi.properties, muikku-forum-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/plugins/forum/rest/ForumThreadReplyRESTModel.java, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss, updates/1.0156/161115_reply_deleted.xml
=> Ftr 2064 discussion reply delete

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-word-definition.js
=> Fix for squashed word definition near right edge of screen

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js
=> Correct material titles in transcript of records view

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
=> Fix for number of correct answers shown after page license and/or producers

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_connect-field.scss
=> Bug 2639 connectfield term shortening

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_audio-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_file-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Show no audio clips message for audio fields that... Wait for it... Don't have audio clips!

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/dao/CommunicatorMessageRecipientDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
=> Moved communicator new message notification back to rest service

muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_item_open.dust
=> ** Fixed #2632

muikku-atests/pom.xml, muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java, muikku-pyramus-oauth/pom.xml, muikku-school-data-pyramus/pom.xml
=> Bump Pyramus references to 0.7.61-SNAPSHOT

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Changed reloadfolder to class change when marking unread/read

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js
=> Removed filtering by curriculum

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Bug 2657 reply all

.travis.yml, muikku-atests/pom.xml
=> Bug 2654 cargo stopping failure on travis

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
=> Better handling and error logging for missing grades

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/DiscussionBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumResourcePermissionCollection.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceDiscussionsBackingBean.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, updates/1.0157/161124_studentforumpermissions.xml
=> Added right for higher ups to edit messages that are not own

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
- fixes #2670 (to show correct answers also shown in evaluation and transcript of records)
=> Better placement for correct answers container

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/IndexedWorkspaceUser.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/WorkspaceIndexer.java, muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
=> Added course staff members to workspace index and free text search

muikku/src/main/webapp/resources/theme-muikku/sass/flex/discussion.scss
=> Forum reply layout fix

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/frontpage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/helppage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-reading.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Removed lazyyt.js so that YouTube clips use lazyframe.js like all other iframes

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/materials-article-details.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/frontpage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/helppage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/article-details.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Free text license

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
=> Remove dotdotdot from connect fields due to performance issues

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceMaterialController.java
=> Workspace material sort fix

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js
=> Fix for lengthy connect field counterparts not switchable by clicking

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Scale YouTube clips to 16:9 page width

muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspacePluginMessages_fi.properties, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
=> Evaluation notifications in new evaluation, now with more information

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
=> Fix for new evaluation treating drafts as answered assignments

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NotificationController.java
=> ** Make dry run configurable in runtime

muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/UserEntityDAO.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/users/UserEntity.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java, updates/1.0158/161207_userentity_updatedbystudent.xml
=> ** Remember which students have updated their info

muikku/src/main/webapp/resources/theme-muikku/sass/_textcontent.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles_backup.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> * Changed list-style-position to outside instead on inside

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Keep current assignment editor data when assignment doesn't change

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java
=> Restore latest evaluation request (if any) when workspace evaluation is removed

muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-assignment-wrapper.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-journal-entries.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-modal-view.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_mobile_evaluation.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars_backup.scss
=> Bug 2692 journal entries

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Close open assignments in new evaluation after they have been evaluated

muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/main-view.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_fi.properties, muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
=> Ftr 2705 workspace sort

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Fix for new evaluation showing correct text field answers as incorrect

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Convert ordinary memo field line breaks to HTML line breaks in evaluation

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml
=> Slightly better connect field drag & drop

muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/main-view.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> New evaluation draft support

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> * remoed verticalFit from magnificPopup

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss
=> * Better readibility for assignment grade in evaluation

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-evaluation-request-confirm.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
=> Make it harder to request evaluation if all assignments haven't been submitted yet

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/journal/CourseJournalPageTestsBase.java
=> ** Fixes #2747 journal test bug

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Added disabled to the send button when message is being sent

muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Word break for user front page messages

muikku-evaluation-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/rest/model/RestAssignment.java, muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-assignment-wrapper.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss
=> Bug 2731 literal evaluation

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Better (if less aesthetic) drafting in new evaluation

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Refactored new evaluation click handlers to cope with handicapped phones

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Forms for assignments to avoid render issues with duplicate field names

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss
=> Ftr 2766 workspace eval form disabled

muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java, muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-card.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/UserEntityProperty.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation-index.scss
- resolves #2764 
- resolves #2765
=> Support for marking evaluation requests as important or unimportant

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataUserGroupListener.java, muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityController.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/users/UserGroupUserEntityDAO.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java
=> Added updating of study programme user group when student update happens

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation-index.scss
=> Bug 2789 custom dialogs

muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
=> Added finnish locale and locale selection for datepicker

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/announcer/model/AnnouncementAttachment.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncerAttachmentUploadServlet.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/dao/AnnouncementAttachmentDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js, updates/1.064/161230_announcement_attachments.xml
=> Added D&D image support for announcer

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementsViewBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/dao/AnnouncementDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/announcer/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js, muikku-core-plugins/src/main/resources/META-INF/resources/widgets/communicator-categories.xhtml, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/announcer/AnnouncerPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/announcer/AnnouncerPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/announcer.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss
Closes #2784 
Closes #1325 
Categories may need further fine tuning but this should be a decent start.
=> Ftr 2784 announcer announcement category filters

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/AssessmentRequestNotificationStrategy.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoPassedCoursesNotificationStrategy.java
=> Bug 2737 study time end notification when studies started

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorMessageSentNotifier.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/events/CommunicatorMessageSent.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
=> Asynchronous sending of notification mails from communicator

muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/announcer/index.xhtml
=> Bug 2787 announcer flexing fixes

muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml, muikku/src/main/webapp/resources/scripts/gui/environment.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_mobile.scss
=> * Changed mobile main navigation menu event to click from hover and

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_mobile_workspace.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace_navigation_narrow.scss
=> * Adjusted workspace mobile navigation

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/guider/index.xhtml, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_en.properties
=> * Fixed locale string issue

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/dao/AnnouncementWorkspaceDAO.java
=> Fix for list announcements SQL crash

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_mobile_workspace.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_sorter-field.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> Ftr 2814 organizer task width

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java
=> ** Fixes #2822

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars.scss
=> * Literal BG color & Exercise opening issue

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepicker_curriculum_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepicker_educationtype_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_user_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/guider/index.xhtml, muikku/src/main/webapp/index.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Ftr 2785 mainfunctions category styles refactoring

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Pre-select current user for new evaluations

muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/main-view.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js
=> Save last used sort in evaluation

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/operations/BinaryMaterialCloneOperation.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/material/operations/HtmlMaterialCloneOperation.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js
=> When cloning materials, also clone their metadata and producers

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataBridge.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataController.java, muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/AssesmentRequestNotificationController.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/dao/AssessmentRequestNotificationDAO.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/AssessmentRequestNotificationStrategy.java
- fixes #2867 (but requires Pyramus 448)
=> Notification of no evaluation activity after the first 60 days of studies

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java
=> ** Check the student's study start date properly

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/login.js
=> * Forgotpassword

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss_management.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/custom-ckeditor-contentcss_reading.scss
=> * Materials rendering fixes

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> ** Fixes #2825 backticks (`) in student-submitted assignments interpreted as MathJax

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> * Changed evaluation assignments clickable area to its wrapper

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-sorter-component.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_sorter-field.scss
=> * Added width and renderer handling for sorter fields when capitalize is

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
=> Ftr 2842 test evaluation materialsview visibility

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataBridge.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataController.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NoPassedCoursesNotificationController.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoPassedCoursesNotificationStrategy.java
=> Bug 2868 nopassed notification

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java
=> Ftr 2881 test evaluation request importance sort

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/schooldatalocal/entities/LocalUserImpl.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/AbstractUser.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/User.java, muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java, muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusUser.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/StudyTimeLeftNotificationController.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java
=> Various fixes for study time end notification

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Block material assessment save while saving

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss
=> Ftr 2831 open evaluation

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/announcer/CourseAnnouncerTestsBase.java
=> ** Fixing bug in announcer test with datepicker allways being in the way

muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials.scss
=> * Fixed borked UL styles in materials view

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/newevaluation/NewEvaluationTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/tor/ToRTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/tor/ToRTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/tor/ToRTestsIT.java
=> Ftr 2899 to r testing

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorTrashRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_fi.properties
=> Added recipient names to trash view

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/data/DataPluginDescriptor.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/data/PermissionDataPluginDescriptor.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/data/PermissionsPluginController.java
=> Added reset option for role permissions

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js, updates/1.065/170202-audio.xml
=> Fix for duplicate audio clip ids

muikku-atests/pom.xml, muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractRESTTest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java, muikku-atests/src/test/resources/muikku-data/test/test-data.sql, muikku-atests/src/test/resources/sql/ui-initial-data.sql
=> ** Might fix random cargo-stop failures

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/fieldio/WorkspaceAudioFieldIOHandler.java
=> Fix for removing previously recorded audio clips

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js
=> Fixed issue with teacher getting error popups from student profile

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> * Removed math wrapper

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
=> Plugin setting to filter grading scales used in Muikku

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js
=> ** Fixes #2811

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_user_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_fi.properties
=> ** Share guider flags from flags list

muikku-mongo-log/src/main/java/fi/otavanopisto/muikku/plugins/mongolog/MongoLogProvider.java, muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoPassedCoursesNotificationStrategy.java, muikku-timed-notifications-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/timednotifications/TimedNotificationsPluginMessages_en.properties, muikku-timed-notifications-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/timednotifications/TimedNotificationsPluginMessages_fi.properties, muikku-timed-notifications-plugin/src/main/resources/jade/assessment-request-notification.jade, muikku-timed-notifications-plugin/src/main/resources/jade/no-passed-courses-notification.jade
=> Ftr 2949 nopassed

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/check-contact-info.js, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
=> Fix for contact info being checked for staff members as well

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementsViewBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_widget_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-announcements.js
=> Fixed issue with some roles not seeing workspaces in announcer

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-reading.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js
- fixes #2516 (well, slightly improves at least)
=> Slightly better navigation/scroll/TOC collaboration in materials

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
=> Filtered grading scales in new evaluation only

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Draft plugin 0.0.3 (simpler and with manual start support)

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js
=> * Added cc icon for workspace front page

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoPassedCoursesNotificationStrategy.java
=> Fixed property used for two distinct things

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/language/LanguageWidgetBackingBean.java
=> Changed locale change to redirect to same view

muikku-core/src/main/java/fi/otavanopisto/muikku/security/MuikkuPermissions.java, muikku/src/main/webapp/WEB-INF/templates/flex-main-env.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml
=> Workspace access for study guiders

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-copy-wizard.js
=> Fix for copied workspace not having specified begin and end dates

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/frontpage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/helppage-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-management.xhtml
=> Upgraded license selector to 0.0.8, which outputs proper CC urls

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js
=> Properly ordered CC icons regardless of license version and url protocol

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/CopiedWorkspaceEntityIdFinder.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
=> When copying a workspace, also copy default license and producers

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/socialnavigation.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-journal.scss
=> Workspace journal draft support

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-activity.js
=> Fix for broken workspace activity popups

muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractRESTTest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/Common.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/PyramusMocks.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/communicator/CommunicatorTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/users/CourseUsersTestsBase.java
=> ** Removing hard coded ports

muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
=> ** Fix #2856 only allow flags to be shared to staff members

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-evaluation-request-confirm.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
=> Remove number of assignments check from Request Evaluation dialog

muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> * Fixes to long user name

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/records.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js
=> Higher journal entry limit for views without journal entry pagination

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Fix for marking messages read/unread in communicator

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusSchoolDataEntityFactory.java, muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/entities/PyramusUser.java
=> Requested changes to how evaluation fees are determined

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusWorkspaceSchoolDataBridge.java
- fixes #2915
- requires Pyramus build (respective issue 482)
=> Also copy additional course descriptions when copying a workspace

muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NotificationController.java
=> Crummy fix to choose the "correct" guidance counselor for students in multiple guidance groups

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java
=> Permanently delete workspace users that are removed from Pyramus

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAssessmentRequestController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorMessageRecipientRESTModel.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTModels.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/profile/ProfileBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/seeker/defaultproviders/UserSeekerResultProvider.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/model/Student.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java, muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
- resolves #3078
- nicknames in new evaluation require Pyramus feature 488
=> More consistent support for students' nicknames

muikku-core-plugins/src/main/resources/META-INF/resources/dust/workspace/workspace-frontpage-teachers.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/profile/profile.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfilePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/profile/ProfilePluginMessages_fi.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
=> Various minor bug fixes to displaying teachers' vacation period

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java, muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java, muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceUserEntityDAO.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
=> Only show workspace teachers on workspace front page

muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_reply.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js
After managing to figure what was going on in the process of retreival I figured a very simple fix for the problem; it's a simple solution by looping on an already existant array; more elegant solutions say using promises to chain and check resulting values would require to refactor the widgets and this only tackles the feature.
Please comment any problems you have with the fix and I'll tackle the comments ASAP.
Fixes #2240
=> Show name of origin in discussion replies

muikku-core-plugins/src/main/resources/META-INF/resources/widgets/dock-environment-evaluation.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/main-view.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_fi.properties, muikku/src/main/webapp/WEB-INF/templates/flex-main-env.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation-index.scss
=> Switch to new evaluation

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SchoolDataSearchReindexListener.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SystemReindexBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/UserIndexer.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/entity/User.java, muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchReindexEvent.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
Closes #3113 
Additionally added support for resuming reindexing process in case it stops for whatever reason.
=> Added staff members' emails to search index

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
=> Prevent double-clicks when submitting an evaluation request

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorTrashRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_tools_message.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_tools_thread.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/communicator/CommunicatorJsPluginMessages_fi.properties, muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
=> Added restoring of trashed messages to communicator

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator-newmessage.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/socialnavigation.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js
=> Prevent enter in text fields from accidentally submitting forms

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJournalBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJournalController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/dao/WorkspaceJournalEntryDAO.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js
=> Changed journal loading mechanisms

muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepicker_curriculum_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/coursepicker/coursepicker_educationtype_filters.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/coursepicker.js
=> Extended Coursepicker filter clickable area

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/frontpage.js
=> * Removed avoimet_verkostot feed from front page

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_ckeditor_theme.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-materials.scss
=> Word counter for memo and rich memo fields

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
=> Fix for requesting evaluation

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
=> More accurate handling for workspace assessment state

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-connect-field-component.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js
Took me a while to figure out what was going on but at the end I devised a solution.
This fixes the actual #3028 mutta there's a situation there that the task was initially mistaken for another and there's actually a bug when updating and publishing resources, this is not part of the scope of that problem but it was researched and a spin off task must be created that contains such data; this is a backend issue that has to be discussed in order to find a solution.
=> Added hide indicators methods and hide indicators during refresh

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
=> Only list active students in new evaluation + notification mail of evaluations

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-visits.js
Fixes #3098 this issue was pretty "interesting", I have absolutely no idea why would anyone try to solve arimethics using eval but well :D this is the fix that makes it work.
=> Removed eval to make fronpage workspace time topics work

muikku/src/main/webapp/index_nonbranded.xhtml
fixed double flex row
Fixes #3125
=> Logged in frontpage bugged

.eslintrc.json
Added formatDate, formatTime and moment to hound globals
=> Added formatDate, formatTime and moment to hound globals

muikku-evaluation-plugin/src/main/resources/META-INF/resources/dust/evaluation/evaluation-assignment-wrapper.dust, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-main.js, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationJsPluginMessages_fi.properties, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_evaluate_modal.scss
=> * Added checkmark for done exercises in new evaluation modal view.

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
=> Possible fix for incorrectly indexed workspaces

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> * Fixed image max-width scaling issue

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsBackingBean.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsPermissions.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/VopsRESTModel.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_view_profile.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_vops.dust, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/guider/index.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss
=> Ftr 3183 guider studies ui

muikku-core/src/main/java/fi/otavanopisto/muikku/session/RestAuthentication.java, muikku-core/src/main/java/fi/otavanopisto/muikku/session/RestSessionControllerImpl.java, muikku-core/src/main/java/fi/otavanopisto/muikku/session/local/LocalSessionRestAuthentication.java, muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/RestSessionFilter.java
=> Fixes user activity for REST calls

muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPagePluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPagePluginMessages_fi.properties, muikku/src/main/webapp/index.xhtml, muikku/src/main/webapp/index_nonbranded.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main.scss
=> Front page message for students whose studies have ended

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss
=> * Fixed issue with sublist elements margins

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/help.xhtml
=> Fix for workspace help page not loading

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
=> Courses based on signup permissions, don't show empty subjects in studies matrix

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTModels.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator-newmessage.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Added some handling in case of archived users

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/VopsRESTModel.java, muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_view_profile.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/records/records_vops.dust
=> Grades in studies matrix

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceUserEntityIdFinder.java
=> Fix for workspace front page not showing properly when signing up to a workspace

muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_en.properties, muikku-evaluation-plugin/src/main/resources/fi/otavanopisto/muikku/plugins/evaluation/EvaluationPluginMessages_fi.properties
=> Don't send notifications when evaluating assignments

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_correct_answers.scss
=> Memo field example answer line breaks

muikku-timed-notifications-plugin/src/main/resources/jade/requested-assessment-supplementation-notification.jade, muikku-timed-notifications-plugin/src/main/resources/jade/study-time-notification.jade
=> Added footer about automated message to messages it was missing for

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-selection/plugin.js
=> Fix for not being able to remove a select field explanation

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator-newmessage.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-frontpage.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/workspace/WorkspaceJsPluginMessages_fi.properties
=> Added link to workspace the message was sent from

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-explanation-widget.js
=> Handle linebreaks and non-breaking spaces in select field explanations

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js
=> Fixed browser navigation in discussion

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumController.java
=> Added span style attribute to whitelist

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
=> ** Fix #3297 NPE in studies view

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
=> Added span style to whitelisted

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java
- resolves #3308 
When receiving a course student updated event, and the study program of that course student has been changed, automatically reactivate the workspace student if the new study program is active.
=> Restore workspace students switching to an active study program

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/templates/workspace-materials-management-view.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-mathjax/plugin.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-editor-html.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-page-editor-html.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/jsf/evaluation/templates/evaluation-view.xhtml, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js, muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
=> Fixed expired mathjax cdn

muikku/src/main/java/fi/otavanopisto/muikku/EnvironmentBackingBean.java, muikku/src/main/webapp/WEB-INF/templates/flex-base.xhtml
=> Moved Google Analytics tracking id to system setting

muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss
=> Break long links and words in communicator.

muikku/src/main/webapp/WEB-INF/templates/flex-main-env.xhtml
=> Incorrect syntax fixed

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/picker/CoursePickerTestsBase.java
=> ** Fixes bugging coursePickerSsearch test

muikku/src/main/webapp/resources/theme-muikku/sass/flex/discussion.scss
=> Bug 3270 discussion thread listing long links

muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss
=> Adds some separation to message topic from message body

.travis.yml, travis-before-script.sh, travis-setenv.sh
=> Sauce Connect 4.4.7 configuration

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_organizer-field.scss
=> Ftr 3046 organizer target boxes do not align

muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java
=> ** Fixes #3347 flag sharing is broken

muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_item.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_item_open.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/discussion/discussion_reply.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js
=> Removes formatTime from JS

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/discussions.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/journal.xhtml
=> Adds js to template and classes to inputs

muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_tools_message.dust, muikku-core-plugins/src/main/resources/META-INF/resources/dust/communicator/communicator_tools_thread.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js
=> Changes to the message read / unread marking

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js
** Fixes #3352 audio saving problems
=> Ask for a sample rate from getUserMedia

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js, muikku/src/main/webapp/resources/theme-muikku/sass/flex/guider.scss
=> Loading animation to profile-courses

.travis.yml, muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java, muikku-atests/pom.xml, muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractRESTTest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/mock/PyramusMock.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/discussions/CourseDiscussionTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/picker/CoursePickerTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/evaluation/EvaluationTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/flags/FlagTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/guider/GuiderTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/indexpage/IndexPageTestsBase.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/course/discussions/CourseDiscussionTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/local/discussions/DiscussionTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/course/discussions/CourseDiscussionTestsIT.java, muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/sauce/discussions/DiscussionTestsIT.java, travis-before-script.sh
Fixes #3345 and also updates wiremock
=> Bug 3345 discussion test fix

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml, muikku/src/main/webapp/WEB-INF/templates/flex-main.xhtml, muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace_navigation_narrow.scss
Closes #2520 
I did not do the thing asked, because scrolling a popup menu especially in mobile is not the first choice. I removed padding and hid some secondary priority elements out of the way.
=> Make fonts and paddings smaller and hide some elements

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_edit_flag.dust
=> Removes unused ids

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
=> Escape plain text memo field html

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
=> Bug 3393 tor ie

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_vars.scss, muikku/src/main/webapp/resources/theme-muikku/sass/flex/communicator.scss
=> differentiates read (old) and unread (new) font colors

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace-material-scripts.xhtml, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/lazyframe.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/lazypdf.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/lazyswf.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-reading.js, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js, muikku/src/main/webapp/WEB-INF/templates/default.xhtml
=> Ftr 3396 update waypoints

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/flags/FlagTestsBase.java
=> ** Test be re-enabled

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-journal.js
- fixes #3418
- changed journal student list to only display active workspace students
- replaced Elastic search of workspace students with a direct database call
- minor optimizing and null checks
=> Fixes for listing workspace journal entries

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusScheduler.java
=> PyramusScheduler changes

muikku-core-plugins/src/main/resources/META-INF/resources/dust/frontpage/widget_workspaces.dust, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/widget-courselist.js, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_en.properties, muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/frontpage/FrontPageJsPluginMessages_fi.properties, muikku/src/main/webapp/index.xhtml
=> Bug 3390 frontpage no workspace messages

travis-after-success.sh
=> Fixes dependencies not following Pyramus.

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/CourseAccessTestsBase.java, muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-management.js
=> ** Fixes "exotic" function declaration in workspace-management.js and

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerWorkspace.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceEntityFileController.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java, muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/model/Workspace.java
Added hasCustomImage to rest endpoints returning workspaces in
* coursepicker/workspaces
* workspace/workspaces
=> Added hasCustomImage to rest endpoints returning workspaces
