otavanopisto/muikku

muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/parser/content/ConnectFieldOption.java
muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/translator/FieldTranslator.java

Fixed simply by truncating connect field terms and equivalents over 255 characters to 255 characters. Hardly an elegant fix but values that long are absurd to begin with, so it makes no sense to modify the database schema to support them.

Fix for bug #500

---

muikku-core-plugins/src/main/java/fi/muikku/plugins/material/fieldmeta/SelectFieldOptionMeta.java
muikku-deus-nex-machina/src/main/java/fi/muikku/plugins/dnm/translator/FieldTranslator.java

Fixed by generating unique option names for options that have an empty name.

Fix for bug #499

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/socialnavigation.js

* Fixed issue #472 where communicator's reply didn't work if caption was empty and it was not filled automatically. Discussion specific textfield handling was done outside if block which was also discussion specific.

* Fixed issue #472

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js

Publishing on Firefox seems to work just fine. There have, however, been reports that publish does not seem to do anything on first click. This might be due to the entire page being reloaded after publish (or unpublish). This could lead to a few seconds of seemingly nothing happening and an impatient user might end up clicking the button multiple times. Fixed by simply toggling the Publish and Unpublish buttons visible/hidden rather than reloading the entire page. Feedback is now practically instantaneous.

Fixes #582

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/evaluation.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/socialnavigation.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-material-editor-html.js

Disabled HTML entities in CKEditor (materials, evaluation, and social navigation)

Fixes #828 (CKEditor HTML entities)

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/lazypdf.js

** Changed lazypdf to close older pdf viewers when 10 or more viewers are open on Firefox

---

muikku-core-plugins/src/main/java/fi/muikku/plugins/workspace/WorkspaceMaterialController.java

Front and help pages of a workspace should always be copied rather than linked

---

muikku-bom/pom.xml

Version 3.2.1 has a CVSS 10.0 vulnerability. That is the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

Upgrade Apache Commons Collections to v3.2.2

---

muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_user_filters.dust
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/guider.js

- added name extension to guider workspaces
- added correct workspace user filter
- upped guider workspace max results to 500
- sort guider workspaces by name
- resolves #1830

Name extensions to guider workspaces (+ miscellaneous guider bug fixes)

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml

Don't show workspace name extension if null or empty (used to have only null check)

---

muikku/src/main/webapp/resources/theme-muikku/Makefile
muikku/src/main/webapp/resources/theme-muikku/sass/_widgets.scss
muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces.scss

** Fixes #2907 @incude in sass files

---

muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java

Closes #2984 
The issue here is that if the OffsetDateTime.now() returned f.ex. "today 13:37+02:00" and we zero the time it will be "today 00:00+02:00" which actually is yesterday 22:00GMT. I.e. the timezone has unknown effect on the outcome.
The problem is f.ex. on line 228 where studyStartDate timestamp is saved as "today 00:00" but the translated date from current time is actually yesterday 22:00. So test of studyStartDate[today] <= "now[millis:0]" is never true for the same start day provided the time zone is not GMT.
This is a proposition and needs to be evaluated to minimize risk for further problems.

Removed zeroing of time in search

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketMessenger.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketPluginDescriptor.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketTicketController.java
muikku/src/main/webapp/resources/scripts/gui/websocket.js
updates/1.068/170313-stale-ws-tickets.xml

- remove past WebSocket tickets on startup
- ignore WebSocket messages with invalid tickets
- dispose old WebSockets without instant reconnect
- do not try to close WebSockets that aren't even open yet
- fixes #3023

Miscellaneous WebSocket maintenance

---

muikku/src/main/webapp/resources/scripts/api/api.js

So after fiddling with the nightmare that IE is I figured it was a caching issue that came from the mApi as there are several layers of catching, I disabled jQuery level one which by default would append a timestamp in order to try to be smart.
I figured I only had to add one line so yes this fix is very short, however we need to give some testing as this affects the way it behaves in all browsers. However since catching doesn't happen is rest endpoints (which is why it works right on chrome, firefox and safari) this seems to only affect IE making it work.
However if required I can make it so that the cache flag is only set to false if the browser is IE11.
Fixes #3041 ja #3040 
Please also do your own testing in a non VM IE11.

Fix problems with deletion and editing communicator messages in IE11

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js

A very simple fix where I simply allow the html to be overriden with the `.html` as it seems that the scrolling would not be affected when doing so. However it is to consider that the optimal answer is to use diffing techiques or manual updates but it's not quite applicable in the context of dust, this fix however instead does less by not allowing the previous html to be removed.
closes #2176

Page should not scroll top when loading more messages in the discussion

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js

Yes that was literally the problem, took a while to found out but since there are two elements one to contain the messages and other to content the settings the message screen superseded the other when the messages was open, so I just make it to show and hide respectably.
Eclipse is making weird changes without even asking me it seems from the formatting.
Fixes #312

Communicator setting view does not work when reading a message

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_item.dust
muikku-core-plugins/src/main/resources/META-INF/resources/dust/announcer/announcer_items.dust
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js

Fixes #3010 this was fixed as discussed with @pkukkon by removing the delete button, in the archived view as well as removing the checkboxs in the items that are archived.
A backend side bug was fixed where the property archived was not being set at all.

Fixing archiving of announcements bug

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace_announcer.xhtml

Fixes #3142 it was a pretty easy fix as only some html was added into the mix, the widget basically handles it all; it just represents a copy of the content that is in the normal announcer outside the workspace announcer.

Added html for the an-categories class

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/discussion.js

This issue was actually all over the discussions but only appeared under a very specific circumstance that was that the parent reply was just cutting the children replies because the request didn't load more. eg.
```
[1]
[2]
[3]
[4]
[5]
---------
[6]
```
Because they were loaded in a separated manner, the 6 answer wouldn't relate to the 5th and so it wouldn't be able to create itself, causing it to crash.
Fixed by adding an accumulative variable that would remember the previous values as well as adding a failsafe mechanism for even when the parent thread does not exist.
Fixes #3173

Fixed course discussions button not working

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/profile/profile.xhtml

As discussed the change address that is shown in the profile is now invisible for non-students and so does not allow change it for such.
Fixes #3171

Made change address link invisible for non-students

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/ForumPermissionResolver.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/AbstractWorkspaceBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/InactiveUserListener.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/WorkspaceBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/security/impl/DefaultPermissionResolver.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/WorkspaceUserEntityController.java
muikku-evaluation-plugin/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/dao/workspace/WorkspaceUserEntityDAO.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

- fixes #3190
Changed all WorkspaceUserEntityController methods that accept a UserEntity to use the default identifier of that user. For example, asking for all workspaces of a user only returns those that are part of their currently active study program.
When a study program of a student is marked as ended in Pyramus, they are automatically removed from active workspaces of that study program only. Earlier implementation would have removed them from every active workspace of their every study program.
Changed workspace permission handling to treat inactive workspace users like they were archived (i.e. permanently deleted). Thus, if a student is removed from a workspace, Muikku will act like they were never even part of it. Naturally they can still sign up for the workspace again, which …

Further fine-tuning of workspace student activity

---

muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss

It was a simple css error, fixed it with the reference of @jjlankinen and it works now.
Fixes #3186

Fixed missing word definition

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncementController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/announcer.js

This fixes #3011 as well as provides a futureproof endpoint for more functionality. This is a rather simple fix and makes sure that editing archived announcements will makes the pop up back to the active list or past for its defect.

Added and used archived property to modify announcements

---

muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorIndexBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/coursepicker/CoursePickerRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/forum/DiscussionBackingBean.java
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/workspace.xhtml
muikku-core/src/main/java/fi/otavanopisto/muikku/auth/AbstractAuthenticationStrategy.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/SchoolDataWorkspaceUserDiscoveredEvent.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/SchoolDataWorkspaceUserUpdatedEvent.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/RestSessionControllerImpl.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/SessionController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/SessionControllerDelegateImpl.java
muikku-core/src/main/java/fi/otavanopisto/muikku/session/local/LocalSessionControllerImpl.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java
muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
muikku/src/main/webapp/WEB-INF/templates/flex-main-env.xhtml
muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml
muikku/src/main/webapp/index.xhtml
muikku/src/main/webapp/index_nonbranded.xhtml

- resolves #3103
Refactored the code for students who have ended their studies. They now only have access to profile, course picker (with no signup), and transcript of records. Workspaces, messages, and announcements have been removed from the environment front page. Teachers and announcements have been removed from workspaces' front pages.
Refactored synchronizing of Pyramus course students so that all of them (except archived ones) also exist in Muikku. Only students who have not yet ended their studies will have their active flag set. This should ensure that everyone's transcript of records show the exact same courses as can be seen in Pyramus.

Better handling of students having ended their studies

---

updates/1.076/170601-communicator_index.xml

Closes #3179 
This index helps with listing the threads in the users' inbox. Trash box is still a problem as it can't be covered by an index due to more complex table joins and JPA restrictions on unions. Separate issue on that.

Ftr 3179 communicator slowness

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestState.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/WorkspaceAssessmentState.java
muikku-core-plugins/src/main/resources/META-INF/resources/dust/guider/guider_profile_workspaces.dust
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace.js
muikku-core-plugins/src/main/resources/META-INF/resources/widgets/dock-workspaces-assessment.xhtml
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_en.properties
muikku-core-plugins/src/main/resources/fi/otavanopisto/muikku/plugins/guider/GuiderJsPluginMessages_fi.properties
muikku/src/main/webapp/WEB-INF/templates/flex-main-workspace.xhtml
muikku/src/main/webapp/resources/theme-muikku/sass/_workspaces.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace_navigation_wide.scss

- fixes #3224
Method to cancel an evaluation request was there but never called. I added the missing pieces.
While at it, I also removed the "evaluation request canceled" state, because it had no real value and wasn't ever fully implemented either. If an evaluation request is canceled, the resulting workspace state is once again either unassessed or graded.
Furthermore, I also added two new states to indicate a pending evaluation request when the workspace has been graded before. This way, canceling an evaluation request will correctly revert to the previous state of unassessed, passed, or failed.
I also removed the obsolete AssessmentRequestState class, which has been replaced by WorkspaceAssessmentRequestState at some point.

Proper sending and canceling of evaluation requests

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptOfRecordsController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsBackingBean.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/TranscriptofRecordsUserProperties.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/VopsWorkspace.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataBridge.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/GradingSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/WorkspaceController.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusGradingSchoolDataBridge.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUserSchoolDataBridge.java

Closes #3202 
- Changed loading of student assessments to load all assessments at once (pyramus/#504)
- Removed loading of Workspace object which propagated to loading of educationtypes and subtypes individually from Pyramus
- User properties were already caching but still changed it to a more explicit format of retrieving the whole userproperty stack at once instead of individual queries

Speedup of vops view

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

- fixes #3250
Some (inactive) workspace students are not yet fully synced between Muikku and Pyramus. PyramusSchoolDataWorkspaceStudentsUpdateScheduler will eventually fix such discrepancies. For now, though, added an existence check and error logging to prevent students missing in Muikku from causing a 500 when listing workspace students.

NPE fix for listing workspace students

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js

- fixes #3141
For both plain memo fields and CKEditor memo fields, example answers appeared between the memo field and its word counter. Also, CKEditor example answers sometimes appeared above the memo field.
Fixed by making memo fields responsible of checking their own answers so that they can maintain the proper order of elements (memo field followed by word counter followed by example answer).

Fix for incorrect location of memo field example answers

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/communicator/index.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/communicator.js

Closes #2952 
Added tracking of browser hash to communicator object so it can detect if the browser goes out of sync. This indicates that the navigation happened outside the Communicator event handlers.

Added hash tracking

---

muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusScheduler.java

- resolves #3402
- increased pause between scheduled runs from 15 to 30 seconds (more
breathing room for other functionality)
- removed storing and canceling of timers (the underlying timer service
is wholly responsible of single action timers)
- log scheduler being called (to pinpoint possible problems)

Pyramus scheduler changes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NotificationController.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataUserGroupListener.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java

Closes #3368 
* Changed notification to look only on the active identifier groups
* Fixed updating of the student identifier in UserGroupUserEntity if it was changed

Bug 3368 notifications wrong group

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/dao/AnnouncementDAO.java

Fixes #3480 active announcements are visible in past announcements

Fixes #3480-ActiveAnnouncementsAreVisibleInPastAnnouncements

---

muikku/src/main/webapp/resources/scripts/gui/dustloader.js

Fixes #3330 Firefox complains about dust file conformance by adding a mimeType

BUG-3330 Firefox complains about dust file conformance

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials.js

I found out what it happens, as it was, when you suddenly close the browser, say press the X button because you are done, no other requests are allowed to happen, hence the property setting just doesn't happen as the 'beforeunload' HTTP events doesn't get triggered, even when it could under some circumstances, the browser just wants to close, period.
So with the bugfix the current area will get saved every time the user scrolls to a new section, that way we are avoiding to use it after the beforeunload event, even when I left the event in place; just to keep the old functionality around; nevertheless, it will only get saved as the user scrolls, if the user does not scroll it simply won't happen, so if you navigate to a material screen and you don't scroll it simply won't save. This is the …

Fixed continue studies is off sometimes

---

muikku/src/main/webapp/resources/scripts/gui/chat.js

Fixes #3561 Don't show chat occupants by default  by adding a new parameter to the converse call. converse now has option of hiding occupants by default (def value false, current value true).

Fixes #3561 Don't show chat occupants by default

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcement-view.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/announcements.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/announcements-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/announcement.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/index.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/main-function.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors/message.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/announcement.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/application-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/container.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/message.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/text.scss

Closes #3691 Some major and minor adjustments for announcer's markup so it follows communicator's markup more closely. Some parts are still prefixed by communicator or announcer names and might be able to be named globally.

Ftr 3691 announcer styling

---

muikku/src/main/webapp/resources/scripts/gui/chat.js

Fixes #3723 Converse crashes if there's an incompatible (non-prebind) keepalive session

Fixes #3723 Converse crashes if there's an incompatible (non-prebind)

---

muikku/src/main/webapp/index.xhtml
muikku/src/main/webapp/resources/theme-muikku/sass/_generic_context-view.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_mobile_frontpage.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/evaluation-index.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-main-functionality.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/frontpage.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/profile.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/records.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/workspace-index.scss

Closes #3727 
Every flex shorthand declarations has been exploded into separate flex properties. Updated slick library to newest version also.

Bug 3727 ie11 carousel broken

---

muikku/src/main/webapp/resources/scripts/gui/chat.js

Works fine on the latest converse version 1/16/2018
The issue with saving and loading configuration is not related to this modifications.
chat.js has limit_room_controls parameter set to true (false by default).
This is a list of removed controlls:
"muc#roomconfig_persistentroom",
"muc#roomconfig_passwordprotectedroom",
"muc#roomconfig_roomsecret",
"muc#roomconfig_membersonly",
"muc#roomconfig_roomadmins",
"muc#roomconfig_roomowners",
"muc#roomconfig_enablelogging",
"x-muc#roomconfig_registration",
"x-muc#roomconfig_reservednick",
"muc#roomconfig_whois",
"muc#roomconfig_presencebroadcast"

Fixes #3243- Creation of temporary room by students

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-material-loader.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-rich-memo-field-component.js
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_evaluation_material_styles.scss
muikku/src/main/webapp/resources/theme-muikku/sass/flex/_workspace-materials-defaults.scss

Fixes #3757 -Workspace materials - counter for memofield
added character counter. excluded /(\s|\r\n|\r|\n)+/g
Changed word-count+container to count-container in both view and styles to make it generic.
Fixed word counter by trimming the String before calculating words. It was showing additional words if there were spaces at the beginning or at the end of string.

Fixes #3757 -Workspace materials - counter for memofield

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js

Fixes #3775 Evaluated material page does not load mathjax
Added a mathjax initializer to a muikku field literals.

Fixes #3775 Evaluated material page does not load mathjax

---

muikku-evaluation-plugin/src/main/resources/META-INF/resources/scripts/gui/evaluation-modal.js

Changed lines that sets the dates from setting the evaluation dates of evaluated assignments and workspaces to current date.

Fixes #3658 -Renew evaluation date when re-evaluating incomplete

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/UserSchoolDataController.java
muikku-school-data-pyramus/pom.xml
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/rest/PyramusRestClient.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/schedulers/PyramusScheduler.java

- resolves #3795; Pyramus REST client will now relay all GET exceptions to caller instead of silently ignoring them
- refactored PyramusScheduler to use ManagedScheduledExecutorService; the change aims to address scheduler timeouts and especially fixes the issue of scheduler fails leading to boththe server and scheduler code attempting a retry, possibly causing unexpected concurrency issues
- refactored UserSchoolDataController to relay problems with school data bridge instead of silently ignoring them
**Note:** Okay to be reviewed/commented but might be better to merge only after issues #3801 and #3802 have been addressed. Due to #3795, views retrieving data from Pyramus are now susceptible to exceptions they haven't take into consideration, leading to rather graceless error views.

Refactored PyramusScheduler and PyramusRestClient GET exception handling

---

muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/events/DefaultSchoolDataWorkspaceListener.java
muikku-school-data-pyramus/src/main/java/fi/otavanopisto/muikku/plugins/schooldatapyramus/PyramusUpdater.java

- fixes #3806 (Muikku didn't react to an existing workspace staff member getting a new role in Pyramus)
- scheduled background synchronization of course staff members now archives those workspace staff members that were removed in Pyramus but Muikku somehow failed to process the related event

Workspace staff member synchronization bug fixes

---

muikku/src/main/webapp/resources/theme-muikku/sass/flex/flex-reading-view.scss

Closes #3829 
This accidentally fixes the layout issue as the original reason for the issue is that one of the announcements has long title that forces the list to bee woo wide.

' Fix for announcement's reading view's layout issue; removed

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocket.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/websocket/WebSocketMessenger.java
muikku/src/main/webapp/resources/scripts/gui/websocket.js

- resolves #3366 (?)
- **client:** changed WebSocket ping frequency from 1 to 10 seconds
- **client:** start pinging only after WebSocket is open
- **client:** removed reconnect on WebSocket error as they close the socket which, too, reconnects
- **client:** only reconnect when WebSocket closes abnormally (see above)
- **client:** changed reconnect delay from 0.2 to 2 seconds
- **client:** initialize WebSocket lifetime listeners before establishing connection (not after)
- **server:** better cleanup of WebSockets (and tickets) that are lost or no longer open
- **server:** discard WebSocket (and ticket) on communication failure
- **server:** separate error handling for problems with WebSocket messages and connections

WebSocket maintenance

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/workspace-materials-management.js

Fixes #3855 -Clicking "Add" produces multiple material type selectors
Additionally:
(workspace-materials-management.js:1183)
solves problem with $('#page-' + workspaceMaterialId).offset() undefined by checking it first
(workspace-materials-management.js:1828)
solves problem with wrong variable name "workspaceMaterialErr" to "err"

Fixes #3855 -Clicking "Add" produces multiple material type selectors

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/item-list.scss

Fixes #3495 Label's edit icons are not in line vertically
Setting flex-shrink to 100 will make the textarea shrink enough so everything will be inline.

Fixes #3495 Label's edit icons are not in line vertically

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/main-function/navbar.tsx

Fixes #3938 Navbar has wrong link to evaluation
Changed link in the item list. Now it points to evaluation2/

Fixes #3938 Navbar has wrong link to evaluation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/announcer/body/application/new-edit-announcement.tsx

Fixes #3877 Announcements for all not showing up
Now announcement creator checks the target groups. If there are 0 of them it makes announcement "publiclyVisible"
announcements with at least 1 target group are not "publiclyVisible"

Fixes #3877 Announcements for all not showing up

---

muikku-atests-plugin-rest-model/src/main/java/fi/otavanopisto/muikku/atests/Announcement.java
muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/AbstractRESTTest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/TestRole.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/PyramusMocksRest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/RestTestRequest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/announcer/AbstractAnnouncerRESTTestsIT.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/plugins/announcer/AnnouncerPermissionsTestsIT.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/announcer/AnnouncerTestsBase.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/announcer/CourseAnnouncerTestsBase.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/rest/AnnouncerRESTService.java

* Fixed createAnnouncement to actually return the created entity
* Changed permission of finding a single announcement so that students can actually view what they can list
Closes #3874

Fixes and tests to announcements

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-math-exercise-component.js

* Fixed error with practice exercises where reloading the page dropped them back to unsubmitted state (check for when the latex actually changes for an image)
* Fixed problem with several math exercises on a page where in some cases a wrong instance was referenced in _updateMathImageSVG.
Fixes #4085

Fixed two bugs in math exercise

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/audiorecord.js

- removes audio clips embedded into html in base64 encoded flac and wav flavors that cause massive overhead
- a shoddy rewrite that only supports flac without wav fallback
- complete redesign required
- resolves #4350

Remove base64 encoded audio clips

---

matriculation-plugin/.gitignore
matriculation-plugin/src/main/resources/META-INF/resources/scripts/gui/matriculation/matriculation.jsx

* Changed highlighting from whole row to just cells in enrolled list
* Added highlighting of conflicting mandatory cells (when exam is in finished list and is being repeat)
* Added highlighting of repeat cell when the same subject is in finished list (ie implied repeat)
* Added warning messages of the above two
* Changed how most of the counts are taken - previously Improbatur grades were the only ones excluded, but now duplicates of a subject are removed if they come from the finished list, allowing repeat mechanism to work despite the given grade (needs to work this way)
Closes #4571

Changed how the mandatory courses are calculated

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/Evaluation2RESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/rest/model/RestAssignmentEvaluation.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/rest/model/RestAssignmentEvaluationType.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/gui/muikku-field.js

The button to show/hide assignment evaluation (or supplementation request) is now visible even after the student has withdrawn their previous answer. This enables students to work on their answer while still seeing what the evaluating teacher said about the assignment. Submitting a new answer hides the information as it is likely to no longer be applicable. Resolves #4589.

Show assignment evaluation even if answer is withdrawn

---

muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-management.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/jsf/workspace/materials-reading.xhtml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/link.tsx
muikku/src/main/webapp/WEB-INF/templates/deprecated/flex-main-workspace.xhtml

* Fixed link in workspace management menu that pointed to a non-existing url
* Fixed two h:links that had outcome="#" which is invalid way to use h:link (outcome should be some jsf resolvable target, which # isn't)
* Removed unnecessary console.log
Closes #4618

Fixed navigation case not resolved errors

---

matriculation-plugin/src/main/resources/jade/enrollment-notification.jade

Enrollment doesn't have property changedContactInfo so the block is not needed
Closes #4690

Removed unused caption from matriculation enrollment email

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/SyncStudentEventHandler.java

Added the same check for chat room membership removal as there is for addition.

Skip attempting chat room membership removal when chat is not enabled

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/memo-field.tsx

If memo field's row value is left empty then we set it to 3 by default to prevent 0 height field.
Closes #4973

4973 - Memo field's default height 

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx

Closes #5025 
When MathJax rendering support were added to every task field it was also enabled to selection field's dropdowns and lists causing them to render [Object object] values for option elements instead of correct value. This happened because StrMathJAX component was added to those fields also which was a mistake.
It's not feasible to add MathJax support for select field's option elements as they cannot contain math formulas provided by MathJax.

5025 - Fixed selection task field's rendering.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/content-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/content-panel.scss

Closes #5092 
This will change the html element order of ToC and Material Content so we will serve the ToC first. ToC is still displayed in the right side of the screen via flexbox order property.

5092 - Place ToC before material content 

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/discussions/DiscussionTestsBase.java
muikku-core-plugins/pom.xml
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/input-contacts-autofill.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/audio-field/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/mathjax-react-loader/mathjax-collector.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/coursepicker/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/selectable-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/touch-pager.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/toolbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/records/body/application/hops.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package-lock.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/package.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/tsconfig.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/websocket.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/webpack.config.js
muikku/src/main/webapp/WEB-INF/templates/error.xhtml
muikku/src/main/webapp/index.frontpage.xhtml
muikku/src/main/webapp/index.xhtml

This PR basically upgrades webpack to webpack 5 for a small optimization boost.
There's not much to be added to it to add speed, as parallel webpack proved not to help and it webpack uses only 1 out of the 8 cores, worse in single thread mode.
Some changes to the JSF were required.

Upgrade to webpack 5

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dropdown.tsx

Fixes #4956 
Based it on the webpack 5 branch which I mistakenly assumed was already merged.
I could cherrypick the changes specific to the dropdown or we could just wait until that one is merged.

Fix dropdown component not to overflow

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/ckeditor.tsx

Closes #5266 
This brings back basic entities support for CKEditor so they are escaped properly.

* Added basic entities escaping back

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/new-workspace.tsx

Locks the new workspace wizard before a template is selected on open.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/main-function/navbar.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/link.tsx

Fixes #5134 by adding a keyboard listener to the link
Also fixes the menu links not working because they were disabled.

5134 Make link components work with keyboard

---

.github/workflows/releaseOrDeploy.yml
releaseOrDeploy.sh

Closes #5310 
Adds github actions deploy key to ssh agent to enable
clone/checkout/commit from different locations than the first checked
repository.

SSH key for maven

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/audio-field/index.tsx

Fixes #5008 
I recommend merging soon as this is a likely memory leak of a track that remained open and never closed, and then started to stack with each recording as the memory wasn't cleaned, but I am not sure, not very well versed on the MediaRecorder API.

Fixes media recorder icon always being visible after click

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/base/index.tsx

Fixes #4992 
Nested relative sources are non-standard according to how materials work and as such I decided to normalize these fields.
The way it's done is that.
1. As default every image must be inside a figure element
2. When there's a link on top of a figure element the link is removed.
Let's be careful with side effects but I checked this and everything seems normal after the change.
With the introduction of the zooming element it should be unecessary to have all this extra nesting.

Removed nesting that caused images not to load properly

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/dropdown.tsx

It does a very simple thing disables the arrow down catching functionality when the content of a tooltip is not a list.
Fixes #5433

Removed arrow down on non-list tooltips

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/iframe.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/h5p.ts

Addds H5P resizing supports to the materials dinamically
It is able to combine it with the lazy loader and the fact scripts are blocked by using its own custom h5p resizer based on the original wordpress based one that has been rewritten into typescript with some tweaks to make it dynamic and speak the H5P protocol.
The original H5P resizer was designed for a static website.
Fixes #5130

H5P support

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx

- Restricted materials behind login now correctly prioritizes rectricted
icon for logged admin users over checked icon if excercise is done also
- Contains some minor code cleaning
- content.tsx (workspace materials)
Resolves #5519

Restricted materials behind login fix

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx

The drag and drop event triggers twice, the computer is too fast when debugger is not open so react has no time to re-render and the drag function catches twice.
This update stores the original material state into a variable rather than relying on the react state which might be off-sync.

fixed drag and drop

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/content.tsx

Fixes the calculation of the material from the source of original materials that caused it to be unable to find the original material from the list.
Now it is capable of switching subnodes in sections.

Fixed calculation of the material from the source

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/index/body/announcements-panel.tsx

Pager is hidden if there is only one page (10 or less) of announcements:
- announcements-panel.tsx
Resolves #5546

Pager is hidden if there is only one page of announcements

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SchoolDataSearchReindexListener.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/UserGroupIndexer.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/IndexedCommunicatorMessage.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserGroupEntityController.java

- Removed definitions from indexed communicator messages where the defined types were not supported by the indexing mechanism
- Changed User Group indexing to have the same layout as other indexers also fixing an issue with permissions within

Indexing clarifications

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/profile.ts

Somehow the wrong original variable without the removing the obsolete value was being used resulting in duplication with items of the same id.
This most likely went through the gaps because the error only occurred if the modification was on the last element.
This is the fix.
Fixes #5695

Deduplication of edits in worklist

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/base/course/materials/CourseMaterialsPageTestsBase.java

we now get scrambled order for fields for answering so test might return as correct
or incorrect answer. This accounts for that.

Fixes sorterFieldWithAsciiMathSupportTest random fail

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/organization/dialogs/edit-student.tsx

Resolves #5721
This removes study program selection from edit student dialog at organization management as the operation the select field was meant to provide is way more complex to be done merely by selecting different study program.
Branch name is misleading as the scope of the issue was changed after branch creation.

Removed study program selection 

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/select-field.tsx

Resolves #5221 
Idea is to show exercises correct answers regardless whether the answer state is PASS or FAIL. Previously we showed the correct answers with examples only when the answer was incorrect.

Showing correct answers with examples to students regardles of the answers state

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/content-panel.scss

Resolves #5748 
This PR fixes issue with math editors toolbar z-index stack. It use to open to the top of the page but stayed behind ToC in desktop modes. This PR fixes the z-index of content-panel__main-container in desktop resolution as in tablet/mobile the ToC is hidden and accessible via drawer functionality.
This PR also solves one issue with pad resolution with content-panel__content elements incorrect display property that caused material view not to render properly when it's contain was not contained within the view port. Usually tables that were too wide caused unwanted page overflow.

5748 math editor stack

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/dialog.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/evaluation.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/voice-recorder.scss

Closes #5827 
Main requirement for mobile devices full screen usage is not to use vh values with height property. When mobile device renders something full screen within the browser and url address bar and possible browser buttons reserves some of thatt browsers viewport area. 
If using `height: 100vh` browsers does not adjust their reported viewport height when pulling up the url address bar and/or button bar, therefore small portion of the page will overflow the screen and is inaccessible. Using height: 100% instead fixes this.
It also seems that using height 100% i evaluation modal views everything works perfectly fine with desktop browsers also.

Fixed potentially mobile issues with evaluation modal's overflowing buttons

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java

Resolves #5852  
- Converts filename into US-ASCII encoded string as other encodings are not really fully supported in header filename in all browsers

Fixes filenames with exotic characters that break http header

---

muikku-atests/src/test/java/fi/otavanopisto/muikku/ui/AbstractUITest.java

Resolves #5879 
Also changes builder address into String format since that was introduced to simplify things.

Fixes testing with Firefox on saucelabs

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/AssesmentRequestNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NeverLoggedInNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NoPassedCoursesNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/RequestedAssessmentSupplementationsNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/StudyTimeLeftNotificationController.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/AssessmentRequestNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NeverLoggedInNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/NoPassedCoursesNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/RequestedAssessmentSupplementationsNotificationStrategy.java
muikku-timed-notifications-plugin/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/strategies/StudyTimeNotificationStrategy.java

- fixes #5933
Notifications asked for Elastic fields that weren't included in the search results. Fixed by returning all fields rather than just id field.

Fixes timed notifications not working properly

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/CeeposPermissions.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/ceepos/rest/CeeposRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/guider/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/body/application/current-student/ceepos.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx

Closes #5982 
Added following permission mappings related to webstore functionality:
LIST_USER_ORDERS, FIND_ORDER, REMOVE_ORDER, CREATE_ORDER, PAY_ORDER, LIST_PRODUCTS, COMPLETE_ORDER
Order removal is no dependent on REMOVE_ORDER permission. Order completion still remain ad admin only feature.
Order creation is now dependent on CREATE_ORDER permission, also available purchases rely on the same permission.
LIST_USER_ORDERS permission is used to check whether we render <Ceepos> component inside Guider view. Also loadStudent function has check for the said permission so we don't try to load data logged-in user should not have access to.

* Added permission checks for products and students orders

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/base/status.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/base/status.ts

- Permissions for discussion functionalities are added "back" whether they were missing
at some point or not. So unneeded functionalities are hidden now for students
Resolves: #6043

6043 Discussion: Student sees buttons they don't need to see

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceJournalEntry.java
updates/1.116/220310_workspacejournalentry_index.xml

Index helps the queries in WorkspaceJournalEntryDAO that use workspaceEntityId, userEntityId, archived, created fields or a subset of them.

Added database index on WorkspaceJournalEntry

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/autocomplete.scss

Fixed autocomplete overflowing over navbar by changes autocomplete container z-index value one step lower.
Resolves: #6094

Fixed autocomplete overflowing over navbar

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/binary/pdf.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/link.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/material-page.scss

- Pdf problem is fixed by using styling to hide/showing link only in mobile and pad views
- The actual problem was only with apples device that did only show picture of pdf first page
but clicking picture didn't active download link at all
Resolves: #6096

6096-pdf-in-the-materials-changes:

---

README.md

Should be deleted since we don't use TravisCI anymore

Deletes TravisCI build badge from README.md

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/chat/ChatSyncController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRecipientsRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/guider/GuiderRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/organizationmanagement/rest/OrganizationUserManagementRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/AssesmentRequestNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NeverLoggedInNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NoLoggedInForTwoMonthsNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/NoPassedCoursesNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/RequestedAssessmentSupplementationsNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/timed/notifications/StudyTimeLeftNotificationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/search/SearchProvider.java
muikku-elastic-search/src/main/java/fi/otavanopisto/muikku/plugins/search/ElasticSearchProvider.java
muikku-rest/src/main/java/fi/otavanopisto/muikku/rest/user/UserRESTService.java

- fixed a bug in which teachers could only see students of their own workspaces but not of their own groups
- fixed a bug in which study guiders could click their own workspace in Guider but the view would crash if that workspace had any students that were not in the groups of the study guider
- fixed a bug which caused lag due to an unnecessary Pyramus call for each student shown in Guider
- resolves #6170

Fixes to student visibility in Guider

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts

Communicator message open bug resolved. It was caused by toggleAllThreads property which didn't go off if there was 0 messages after deleting last one and with that said there were situations where active toggleAllThreads affect other functionalities which lead to this original bug.
Resolves: #6176

Communicator message open bug resolved

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/mathjax.ts

Closes #6258 
This fixes `\sphericalangle` symbol's rendering as part of formula in the MathEditor

* Fix for certain symbols rendering inside matheditor's formula

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/workspace.tsx

Workspace users data loads data again between page changes. Before if changing between already loaded users page and one another, user list was holding earlier fetched list and search query was missing. This is easy compromise to prefent confusing users when changing between workspace pages.
Resolves: #6243

Workspace users data loads data again between page changes

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/announcer/AnnouncerAttachmentUploadServlet.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorAttachmentUploadServlet.java

Fixes issue where new Java injects baseUrls before they are programmatically initialized and they remain null forever.

Fixes baseUrl for attachments

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/helpers.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceJournal/body/application/workspace-journals-list-item.tsx

- Setting current diary is now done by clicking the diary name or comment link
- Fixed bug where changing user filter would not update loaded comments array in redux state which caused crashing as changing user between users would not load the comments again even though comments would been missing.
Resolves: #6364

Diary opening changes and bug fixed:

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceManagement/body/management.tsx

Current solution is only temporary fix for workspace management description blank problem. The actual problem still lies in ckeditor component that for some reason doesn't set data correctly. This pr might change later
Resolves: #6415

Temporary solution. Ckeditor needs work.

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/audio-field/index.tsx

Closes #6400
This affects audio record field when it is polyfilled (old browsers?). It's a simple change but probably safe to manually test with more cases before rollout.

Changed JS url to not unnecessarily depend on faces

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/button.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-book.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-editor.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/note-list.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/colors.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/buttons.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/notebook.scss

- notebook item has show content buttons
- notebook item shows overflowing content if closed
- notebook editor focus on title input when opened
- notebook showOpened items are saved to localstorage
- content tab panel active tab is saved to localstorage
- delete button contrast changes
Resolves: #6491

6491 notebook after review and testing fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/index.tsx

Closes #6505 
Solves the issue of MathQuill loading before JQuery by rolling back to previous version of MathQuill. This is a quick fix and by rolling back we break \xrightleftharpoons symbols functionality which was added with the newer forked MathQuill version.
However students are in the need of functional matheditor and we need to fix this issue first and then investigate how we can make the newer version to work optimally.

* Rollback of MathQuill as it seem to break matheditor occasionally

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application.tsx

Name extension is added back to evaluation workspace select option if it exist
Resolves: #6521

Name extension added back to evaluation  workspace selectt

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/note-book/notebook-pdf-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/table-of-content-pdf-dialog.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/helper-functions/dates.ts

IsOverdue would check date based to whole time value including date + time. Now it only check against day value of date.
Pdf background scrolling disabled from table of content and notebook pdfs
Resolves: #6574

6574 note overdue validating by day

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/signature-update.tsx

Communicator signature dialog ckeditor should be now visible again with correct value.
Resolves: #6588

Ckeditor dissapearing bug fixed

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/containers/main-function.tsx

Unactive student guiders are not anymore loaded in records.
Resolves: #6599

unactive student guiders are not anymore loaded in records

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java

- prevent non-course students from sending interim evaluation requests
- fixed wrong course student identifier in interim evaluation requests
- ignore interim evaluation requests already made by non-course students

Interim evaluation fixes

---

muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/guidancerequest/GuidanceRequest.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/guidancerequest/WorkspaceGuidanceRequest.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/material/model/HtmlMaterial.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceMaterialAudioFieldAnswerClip.java
muikku-core-plugins-persistence/src/main/java/fi/otavanopisto/muikku/plugins/workspace/model/WorkspaceMaterialFileFieldAnswerFile.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/oauth/AccessToken.java
muikku-persistence/src/main/java/fi/otavanopisto/muikku/model/oauth/RequestToken.java

Fixed a bunch of annotation-related warnings that were present in console
* `GuidanceRequest` / `WorkspaceGuidanceRequest` had inheritance backwards, inheritance strategy should be specified in the superclass and it's completely ignored in the subclass
* `@PrimaryKeyJoinColumn` was specified in classes that didn't have JOINED or any inheritance strategy what so ever. This should be used only in cases with JOINED inheritance strategy
* Cache annotations are ignored (as per warn in console) for subclasses so they were removed. In these cases the superclass had the same annotations which are still present

Annotation-related warning fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/pedagogical-support-form/index.tsx

Added two new study programme that can use uppersecondary pedagogy form:
- Aikuislukio
- Nettilukio/yksityisopiskelu (aineopintoina)
Resolves: #6717

Added two new study programme that can use uppersecondary pedagogy form

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/main-function/messages/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message-editor/answer-message-drawer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/message-view/message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/body/application/messages.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/new-message.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/communicator/dialogs/signature-update.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/messages.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/util/base-main-function.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

When clicking item from search result list in communicator doesn't anymore crash. Clicked item loads data now correctly and sets folder filter correctly respectly what clicked search item folder property holds. Also little communicator frontend code cleaning related previously done api refactor.
Resolves: #6752

6752 viestimen haku avaa hakutulosketjun vaarasta kansiosta

---

muikku-core-plugins/pom.xml

This cleans the compiled frontend files (generated and dist) in maven clean phase. As the frontend compilation doesn't seem to reuse the files in any way (like partial recompilation etc), it could be a useful addition to ensure that the stage is clean for a full build.
Are there any unintended consequences that come to mind?

Added maven-clean-plugin to remove the compiled frontend in clean phase

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/ckplugins/muikku-mathjax/plugin.js
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/lib/mathjax.ts

Closes #6900 
This PR only updates mathjax to the most recent 2.x version which we can use as we cannot migrate easily to 3.x version yet.
Mathjax 2.7.9 includes following changes:
* https://github.com/mathjax/MathJax/releases/tag/2.7.8
* https://github.com/mathjax/MathJax/releases/tag/2.7.9

* Updated mathjax to 2.7.9

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/material.ts
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/confirm-remove-attachment.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-editor/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/workspaces/index.ts

Changes:
- Material attachments and images can be now added even after material title name has been changed
- Attachment url paths are updated as well when material title name has been changed
- Attachment urls are now hidden
Resolves: #6916 #5002

6916 kuvan lisääminen sivulle ei onnistu tietyssä tilanteessa

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/dao/CommunicatorMessageDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/search/SchoolDataSearchReindexListener.java

Käänteinen indeksointijärjestys viestimen viesteille.
1. Haetaan suurin CommunicatorMessage.id (jos indeksoinnin aikana tulee uusia viestejä niin ne indeksoidaan tallennusvaiheessa, joten ei pitäisi olla ongelmaa niiden suhteen), tallennetaan nykyiseksi indeksointikohdaksi
2. Haetaan batcheissä läjä viestejä käänteisessä id-järjestyksessä alkaen tallennetusta id:stä
3. Indeksoidaan batchin viestit ja pidetään kirjaa siitä, mikä on pienin id, joka batchissä on nähty
4. Batch valmis, valmistaudutaan seuraavaan
a. Jos batch oli vajaa ja indeksi on edelleen > 1 niin oletettavasti alkupäästä on poistettu viestejä -> lopetetaan
b. Vähennetään pienimmästä batchistä löytyneestä id:stä yksi ja siirrytään seuraavaan batchiin, jos päästiin nollaan -> lopetetaan
c. Muutoin id on edelleen > 1 ja batch …

Reverse communicator reindex order

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/workspace/rest/WorkspaceRESTService.java
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/actions/workspaces/index.ts
muikku-core-plugins/src/main/resources/META-INF/resources/swagger.yaml

Workspace producers list endpoint rework:
- Endpoint now accepts producers as list of string and returns newly created producers list back
- Simplifies frontend and backend code
- Delete endpoint removed as its not anymore needed
- Producers order in list won't be affected how fast or slow backend handles multiple single endpoint calls
Resolves: #6932

6932 kurssin tuottajien nimet vaihtelevat listassa paikkaa

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/binary/image.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/static/image.tsx

Readspeaker locale fixed. Now Readspeaker should read correct message when reading images. 
Why Readspeaker reads alt text and not following rs_skip_always rules when manually selecting content is unknown mystery, also if there are two images side by side Readspeaker will not read latter one if it is not followed by some kind of text content.  Both these are probably related to Readspeaker itself so its not Muikku problem directly.
Resolves: #6939

Readspeaker image wrong localle fixed

---

muikku-atests-plugin/src/main/java/fi/otavanopisto/muikku/atests/AcceptanceTestsRESTService.java
muikku-atests/src/test/java/fi/otavanopisto/muikku/rest/test/SystemRESTTestsIT.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/transcriptofrecords/rest/TranscriptofRecordsRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/MuikkuParamConverterProvider.java
muikku-core/src/main/java/fi/otavanopisto/muikku/rest/SchoolDataIdentifierParamConverter.java

Allows SchoolDataIdentifier to be parsed by JAX-RS meaning that SchoolDataIdentifier can be used as a type for `@PathParam`s and `@QueryParam`s. There is one example endpoint changed in this PR.
The motivation for this change is that it could reduce the amount of repetitive code converting Strings to SchoolDataIdentifiers in most endpoints and checking their null status (PathParams are fine without null check [the platform will block the request], QueryParams should still be checked if relevant).
The parsing goes as follows
- If the string is blank (null, empty or whitespace-only), the returned SchoolDataIdentifier is null.
- Otherwise the string is fed to `SchoolDataIdentifier.fromId` and if it parses successfully, the object is returned, otherwise a 400 Bad Request is thrown
This should …

SchoolDataIdentifier ParamConverter

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/content-panel.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/tabs.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/toc.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceHelp/help/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/workspace/workspaceMaterials/materials/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/en.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/locales/translations/fi.json
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/content-panel.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/tabs.scss

Added content-panel__navigation-close element to make content panel navigation more accessible for keyboard users:
- simple close button
- some style changes for button
- couple new locale added
Materiaalit:
Ohjeet:
Resolves: #6861

6861 wcag 1.3.1, 2.1.1 ja 4.1.2  mobiilinakyman sivuvalikossa on isoja saavutettavuusongelmia

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/AlternativeStudyOptions.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java

Tiputettu ohjaamossa ja opinnoissa näkyvistä suoritettujen / suoritettujen pakollisten kurssien lukumääristä pois aineet, jotka ovat toisensa poissulkevia, eli matematiikka, äidinkieli ja uskonto.
Yksittäisiä suorituksia ei siivota listasta. Niiden kohtalo jää myöhemmin arvioitavaksi, koska ei ollut ihan selvää, mitä kaikkea tiedoista ylipäänsä käytetään. Eli jos esim. olisi valittuna MAB, niin MAA:n kurssisuorituksia voi tulla endpointista läpi, mutta niitä ei lasketa summiin.
Closes #7154

Korjattu ohjaamon ja opintojen suorituslukumäärien summat

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/CommunicatorController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/UserRecipientController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/communicator/rest/CommunicatorRESTService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/users/UserEntityController.java

isActiveUser:ia täsmennetty
* Jos aktiivisuutta kysytään `UserEntity`:llä, se selvitetään `UserEntity`:n default `UserSchoolDataIdentifier`:n avulla
* Arkistoitu `UserEntity` -> ei aktiivinen käyttäjä **UUSI RAJAUS**
* Arkistoitu `UserSchoolDataIdentifier` -> ei aktiivinen käyttäjä **UUSI RAJAUS**
* Jos aktiivisuutta kysytään `UserSchoolDataIdentifier`:llä, tarkistetaan onko annettu identifier default identifier, jos ei ole -> ei aktiivinen käyttäjä **UUSI RAJAUS**
Muuta
* Siistitty ja uudelleenjäsennelty `UserRecipientControlle`:a, eri lohkot nyt samassa järjestyksessä
* Poistettu duplikaattikoodia `CommunicatorController`:sta, samat `UserEntityController`:ssa

Lisätty ehtoja aktiivisen käyttäjän tarkistamiseen

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/matriculationExaminationSelectLists/matriculation-examination-selector-components.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/matriculationExaminationWizard/steps/matriculation-examination-enrollment-information-new.tsx

First select option value is now always "" string as it should be, so validation could work correctly
Resolves #7193

"empty" option value is now correctly set to be "" string

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/general/assignment-info-details/helper.ts

Assignment info table now correctly shows only evaluated assignments and take account whether there is hidden assignment and if student has already answered to assignments that are hidden.
Resolves: #7213

Assignment info table assignment visibilite bug fixes

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/hops/index.ts

Hops is now correctly reseted in guider after closing student dialog
Resolves: #7255

Hops is now correctly reseted in guider after closing student dialog

---

muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Closes #7209 
**HUOM!**
Nyt ReadSpeaker ei lue enää mitään piiloitettua sisältöä eli jos tälläiselle on ollut tarvetta se tarve poistuu nyt.
Samaten harkkatehtävien palautteita, jotka ovat piilossa siihen asti kunnes käyttäjä on palauttanut tehtävän, ReadSpeaker ei onnistu lukemaan vaikka niiden piilotus on poistettu ilman että koko sivu pitää ladta uudestaan. Tälle emme voi mitään.
Vaihtoehtoisesti voimme tutkia myöhemmin jos tekisimme erllisen preprosessoinnin kaikille harkkatehtävien palaute laatikoille jolloin lisäisimme niihin ohjelmallisesti **rs_skip** class:in ja poistaisimme tämän piilotetun sisällön lukueston.

* Sort of fix for RS reading/speaking hidden content

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java

When figuring out the state of a course, also consider supplementation requests that have been marked as handled but not removed.

Fix for study activity supplementation requests

---

muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/AssessmentRequestController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/assessmentrequest/rest/AssessmentRequestRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationController.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/EvaluationRESTService.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/evaluation/dao/SupplementationRequestDAO.java
muikku-core-plugins/src/main/java/fi/otavanopisto/muikku/plugins/hops/rest/HopsRestService.java
muikku-core/src/main/java/fi/otavanopisto/muikku/schooldata/CourseMetaController.java

Changed methods returning the latest supplementation request to only return one if it hasn't been handled yet (i.e. not superseded by a newer evaluation action).

Fixes for determining the existance of supplementation requests

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/base/vars.scss
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/sass/elements/rich-text.scss
muikku/src/main/webapp/WEB-INF/templates/base.xhtml

Fixes #7221 
Looks for a rich text inside a tag with lang="ru" .

noto sans for cyrillic texts

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/fields/better-math-field/field.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/base/material-loader/index.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/evaluation/body/application/evaluation/evaluation-material.tsx

Fixes follwing issues:
- mathfield readonly state not changing when canceling assigment returning
- evaluation not showing answer counter fixed
Resolves: #7363 #7361

7363 matikkatehtavaa ei voi muokata kun peruuttaa palautuksen

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guardian_hops/body/application.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/guider/dialogs/student/hops/hops.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/hops/body/application.tsx

Added two missing studyprogrammes to give access hops matriculation:
- Aineopiskelu/valmistuneet
- Kahden tutkinnon opinnot
Resolves: #7367

Two studyProgrammeNames added to give access to hops matriculation

---

muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/language-profile/body/application/cv.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/language-profile/body/application/cv/skill-level.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/language-profile/body/application/cv/stars.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/components/language-profile/body/application/initialization/footer.tsx
muikku-core-plugins/src/main/resources/META-INF/resources/scripts/src/reducers/main-function/language-profile/index.ts

- corrected star values
- skill levell initialization at the skill level component if new language is added
- disables save once the save is successful, so you can't spam it. 
- removes cv language if language is removed from initialization
closes #7450

CV fixes for language profile
